### ISSUE TITLE
Vulkan support?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [MadDeCoDeR/Classic-RBDOOM-3-BFG#1]
Hello.

Saw this respo over at rbdoom 3 somewhere and thought that it was great someone decided to fork and continue where rbdoom 3 left off, especially since it seems abandon now.

Anyways, I am wondering if you will attempt to add Vulkan support from vkdoom 3 to here at all? Robert attempted to this over at RBDoom 3, but he never finished it. I was wondering if you had plans to do it here? I feel like Vulkan would resolve a lot of the performance issues with shadow mapping and such.

**Comment by RinMaru** [comment]
one day.
