### ISSUE TITLE
Audio and video not synchronized in intro videos

### ISSUE THREAD

**Issue by Rathmox** [MadDeCoDeR/Classic-RBDOOM-3-BFG#117]
**Describe the bug**
Audio and video are not synchronized, video is late in starting videos.

**To Reproduce**
1. Start the game
2. Audio and video are not synchronized

**Expected behavior**
Audio and video synchronized

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 1.3.0

**Additional context**
Doesn't happen on RBDoom 3 BFG

**Update**
It looks like the intro video is played incorrectly, I tested it with a video editing software, it's really wierd, the intro sound plays too fast but video is ok, but it happens only during the Bethesda Logo

**Comment by Rathmox** [comment]
I looked a bit to it, sound plays a bit too fast

**Comment by MadDeCoDeR** [comment]
Applied some of the changes they did to my audio code on RBDOOM and I hope now it is synced

**Comment by Rathmox** [comment]
I just tested (thanks Github Actions).
It works perfectly

With the same bug as RBDOOM which is that sound cuts just before the end of the video

**Comment by Rathmox** [comment]
Thanks for the fix
