### ISSUE TITLE
Broken video settings: only one fullscreen resolution

### ISSUE THREAD

**Issue by Rathmox** [MadDeCoDeR/Classic-RBDOOM-3-BFG#118]
**Describe the bug**
There is only one fullscreen resolution in the display settings which is my 2 screens combined

**To Reproduce**
1. Start the Game
2. Open Doom 3 BFG
3. Open settings
4. Go to system
5. Look at the fullscreen resolutions

**Expected behavior**
Resolutions for each one of my monitors

**Screenshots**
![image](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/assets/55508107/7a49065c-da97-4301-9a82-fe0675049528)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Video driver: NVIDIA Proprietary
 - Version 1.3.0

**Additional context**
Doesn't happen on RBDoom3BFG

**Comment by MadDeCoDeR** [comment]
Have you try to run it with wayland?

**Comment by Rathmox** [comment]
No
But using wayland with my GPU breaks a few things like sleep mode so I keep X11

**Comment by Rathmox** [comment]
Using wayland fixed it, but I need it to work on X11

**Comment by MadDeCoDeR** [comment]
BTW. RBDoom uses a static list of resolutions. Which on it's own can cause many issues, sadly the issue is SDL2 and X11, for some reason SDL2 can't read properly the number of monitors and their resolutions from X11.
That's also the reason why DOOM BFA prefers Wayland over X11

**Comment by Rathmox** [comment]
Ok I see

**Comment by MadDeCoDeR** [comment]
Great news!!!
I figure out how to make SDL2 and X11 to play  along together. I had top add libxrandr on the action script.
I tested it on my Steam Deck (X11) and not only it returns the available resolutions but also it can detect multiple monitors.
If you want to see it check the latest nightly build

**Comment by Rathmox** [comment]
It didn't my latest issue in #119 but now resolution works.
