### ISSUE TITLE
something is wrong here

### ISSUE THREAD

**Issue by rstevenson1976** [MadDeCoDeR/Classic-RBDOOM-3-BFG#12]
![screenshot at 2018-11-09 06-58-04](https://user-images.githubusercontent.com/12461190/48289239-b45d8a80-e43c-11e8-8044-ed9fa4b7292d.png)
when using the gravity gun, or when I get hurt, there's no transparency, just solid white

**Comment by rstevenson1976** [comment]
![screenshot at 2018-11-09 16-59-31](https://user-images.githubusercontent.com/12461190/48290427-d78a3900-e440-11e8-8bf8-60d025da9dbf.png)

**Comment by MadDeCoDeR** [comment]
Graphical settings?

**Comment by rstevenson1976** [comment]
1080p60hz, other than that, just all the defaults are ticked

**Comment by MadDeCoDeR** [comment]
Which build? debug, release or retail?

**Comment by MadDeCoDeR** [comment]
Go to advanced options and disable HDR and soft shadows

**Comment by rstevenson1976** [comment]
ok, I'll give it a try

**Comment by rstevenson1976** [comment]
no menu option for HDR, and disabling soft shadows didn't do anything

**Comment by rstevenson1976** [comment]
using gog version of game with the version of rbdoom that doesn't have effed up doom 1 and doom 2 players, this one

**Comment by MadDeCoDeR** [comment]
Are you using THIS port or the original? In this port there is Advanced Options in the Original or older ones there isn't

**Comment by rstevenson1976** [comment]
oh, must be the original then, lutris installed it, I assumed it was this one

**Comment by MadDeCoDeR** [comment]
You can ask him to install the latest version of this one. Is way better.

**Comment by rstevenson1976** [comment]
seeing that what I assumed was the original was the one from the repos where the other 2 games are unplayable

**Comment by rstevenson1976** [comment]
ok I'll try installing this one myself

**Comment by rstevenson1976** [comment]
I built the latest binary from the latest code, the problem is still there

**Comment by MadDeCoDeR** [comment]
Ooh there is also and that https://pcgamingwiki.com/wiki/Doom_3:_BFG_Edition#Screen_flashes_white_when_taking_damage_.28RBDoom3BFG.2FClassic_RBDoom3BFG.29

**Comment by rstevenson1976** [comment]
disabling motion blur while enabling smaa solved it, you can close this issue now, but I suggest making a note of this somewhere for other people that have the same issue
