### ISSUE TITLE
Serious random input lag on Classic Doom

### ISSUE THREAD

**Issue by Rathmox** [MadDeCoDeR/Classic-RBDOOM-3-BFG#120]
**Describe the bug**
Input lag on Classic Doom even in the menus from 1 to 5 seconds

**To Reproduce**
1. Start Doom or Doom II
2. Try opening the menu
3. The menu takes multiple seconds to open

**Expected behavior**
Instant input reactions

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Video driver: NVIDIA Proprietary
 - Version 1.3.0

**Additional context**
Doesn't happen on RBDoom3BFG

**Comment by MadDeCoDeR** [comment]
Thanks for reminding me to re apply that little hack.
Check the latest nightly build

**Comment by Rathmox** [comment]
Input lag in not random anymore and the game is totally playable.
But the menus still take around 1sec to respond

**Comment by Rathmox** [comment]
My latest issue was probably due to an old config that got fixed when I closed the game or something like that
