### ISSUE TITLE
Use DOOM2.WAD textures for TNT Evilution and The Plutonia experiment

### ISSUE THREAD

**Issue by Rathmox** [MadDeCoDeR/Classic-RBDOOM-3-BFG#123]
Some textures were changed in the BFG edition. But when running TNT Evilution and The Plutonia experiment, the game loads the textures from these WADs.

For consistency reasons it could be interesting to use DOOM2.WAD textures

Example with the health pak

DOOM II MAP01:
![image](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/assets/55508107/deaa8399-bc51-460f-ba71-8ede2b4e869c)

TNT: Evilution MAP01:
![image](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/assets/55508107/db114a6b-1b92-4f84-989f-23b7fd5e4c9f)

**Comment by MadDeCoDeR** [comment]
That's not a bug. That's a feature.
Final DOOM WAD files are IWADs and similar to DOOM2.WAD they are loaded alongside the BFA wads (newopt.WAD, ua.WAD).
I didn't that much add support for them but instead I enabled the additional expansions that were already available on DOOM 2.
If you check you will notice that No Rest for the Living and Master Levels use the DOOM 2 assets, and that's because they are just map packs that are loaded alongside DOOM2.WAD

**Comment by Rathmox** [comment]
That's why, to maintain consistency, I'm asking if it's possible to keep DOOM2.WAD textures and load only maps and logos from TNT Evilution

**Comment by Rathmox** [comment]
It made an infinite loop, I had to kill the process

**Comment by MadDeCoDeR** [comment]
NERVE and MASTER Levels have less than 32 Maps.There is always and the option to load a mod that replaces the crosses with pills (or vice versa) on each expansion.
In New-Parameters.txt:
-file ex <1,2,3,4,5>	   : Allowing you to load specific mods per Doom 2's expansions (the ex is ignored on Doom 1). 1=Doom2, 2=TNT, 3=Plutonia, 4=Master Levels, 5=No Rest For The Living

**Comment by Rathmox** [comment]
ok I see.
So at the end, it's impossible to use only TNT and Plutonia new files (maps, texts and specific textures) and use DOOM II files for everything else ?

**Comment by MadDeCoDeR** [comment]
Sadly yes. Even if I edit the expansion details to load DOOM2 and Final DOOM the med paks would still be the ones from the final DOOM WADs

**Comment by Rathmox** [comment]
I would requiere patching the Final DOOM Wads
I can do it but it would not be accessible to everyone

**Comment by MadDeCoDeR** [comment]
I think MIWA mod might be able to help here: https://forum.zdoom.org/viewtopic.php?t=53776
That mod not only changes the med paks from pill to cross but also you can do the reverse (from cross to pill).
It's one of the very first mods I have manage to load to the engine

**Comment by Rathmox** [comment]
I works but uses copyrighted assets.
In my opinion, be best idea would be to load DOOM2.WAD with the Final DOOM WADs. At first sight it would not change anything, but it would be loaded in the same way as any other PWAD in the folder and would allow editing the WAD to play the censored version

**Comment by MadDeCoDeR** [comment]
The editting is not limited to any asset. If you load a mod with new Maps they will replace the original Maps. MIWA is conceptually the best way to approach this.

**Comment by Rathmox** [comment]
True.
You can add this if you want but I don't know if you want to ship the MIWA files or not

**Comment by MadDeCoDeR** [comment]
I won't. I'm already considering to move the BFA WAD files to the BFA Assets repo (They are not 100% self made assets).

**Comment by Rathmox** [comment]
Ok I see
