### ISSUE TITLE
Game crashes after intro videos

### ISSUE THREAD

**Issue by MrEWhite** [MadDeCoDeR/Classic-RBDOOM-3-BFG#129]
**Describe the bug**
Starting with [this nightly release](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/releases/tag/nightly-2023-10-01-12-51-1696164719), the game crashes after the intro video. Any releases before that work fine.

**To Reproduce**
Start the game up, it crashes.

**Desktop (please complete the following information):**
Windows 11 Pro
Nvidia RTX 4090 w/ driver 545.84
Intel i9 13900k
EVGA Z790 Dark
32GB DDR5 RAM

**Additional context**
Attached is the log file generated with "+set logfile 1" from the latest stable release "Version 1.3.0 mini patch."
[qconsole.log](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/files/13061376/qconsole.log)

**Comment by MadDeCoDeR** [comment]
Check the latest nightly build to see if the error persist

**Comment by MrEWhite** [comment]
> Check the latest nightly build to see if the error persist

That fixed it!

**Comment by MadDeCoDeR** [comment]
Reuploaded 1.3.0 mini patch with the actual fix. Closing issue
