### ISSUE TITLE
Crash when starting with "com_game_mode 3" and pressing JOY1 for Campaign

### ISSUE THREAD

**Issue by mmillar-bolis** [MadDeCoDeR/Classic-RBDOOM-3-BFG#131]
**Describe the bug**
When already having a controller connected to the system, if I execute `DoomBFA.exe` with `set com_game_mode 3` either as a command line argument or declared within `autoexec.cfg`, the program successfully enters the mouse-driven version of the Doom 3 menu. Additionally, if I press any button on the controller besides `JOY1` or `JOY2`, the interface buttons will dynamically switch to joystick labels, while still in the mouse-driven version of the Doom 3 menu (see screenshot below). While the highlighted menu options cannot be changed by pressing `JOY_DPAD_LEFT` or `JOY_DPAD_RIGHT`, if I press `JOY1` for Campaign mode, the program silently crashes.

Alternatively, if I press the `JOY2` button, the menu will exit to the Game Select screen, and upon selecting Doom 3, the menu will now be the vertical gamepad version of the Doom 3 menu. From there, crashes based on menu item selection no longer occur.

**To Reproduce**
1. Connect a game controller to the system.
2. Run `DoomBFA.exe +set com_game_mode 3`.
3. Press `JOY1` button for campaign.
4. Exhibit silent crash to desktop.

**Screenshots**
![screenshot001](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/assets/62162171/9406f97c-9459-4ddd-ab09-dbd7e89d0397)

__Desktop__
 - OS: Windows 10 x64 (21H2)
 - GPU: Nvidia GeForce RTX 2060
 - Version: Doom BFA 1.3.0 win-x64 Nov 4 2023 21:03:03

**Additional context**
[qconsole.log](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/files/13330446/qconsole.log)

**Comment by MadDeCoDeR** [comment]
Hi, check the latest nightly build

**Comment by mmillar-bolis** [comment]
Apologies for the late response. Grabbed the nightly and everything appears to be working well after your fix! Very clever and thank you so much!
