### ISSUE TITLE
Black Spots on Screen when HDR is on

### ISSUE THREAD

**Issue by ScarabParamit** [MadDeCoDeR/Classic-RBDOOM-3-BFG#14]
Exactly like in this topic:
github.com/RobertBeckebans/RBDOOM-3-BFG/issues/357

First i tried RBDoom 3 from 2016 related to this post, had "black ink" on screen and turning SSAO off fixed problem.
Then i found this updated variant and have same problem with black spots, but i have to turn HDR off, turning SSAO off gives nothing...its bad cause this version runs MUCH better while i prefer HDR over SSAO.

DOOM3 BFG GoG version.

**Comment by Tarryem** [comment]
Do you have HDR tone mapping on? r_hdrAutoExposure should be set to 1

**Comment by MadDeCoDeR** [comment]
If I knew how to fix it this issue shouldn't have even come to existance

**Comment by ScarabParamit** [comment]
Changeing "r_hdrAutoExposure" can be set in menu, right? Is on, but there was no change even with off.
It had no effect even in ealier version from 2016. It looks like for many something else cause this.
So...i understand its unfixeable?
Then only thing i can do is set brightess to 100% and use all shadows =/

**Comment by MadDeCoDeR** [comment]
For now try to disable SSGI (from launcher), adaptive tonemaping HDR, SSAO and filmic post process effect

**Comment by MadDeCoDeR** [comment]
Well what can I tell you. When I disable all of them and then enable the HDR I usually don't get the black spots

**Comment by ScarabParamit** [comment]
O! So you have same problem?
Can you describe step by step what you do when you play?
Thank You.

**Comment by MadDeCoDeR** [comment]
Well I normally launch the game through the launcher and make sure the SSGI Option was off.
Then on the Advanced Options I disabled the "Adaptive Tonemaping HDR", "SSAO" and the "Filmic Post Process" Options and then disable and re enable the HDR and that's it.

**Comment by ScarabParamit** [comment]
Ok...i can confirm it works...
SSGI NEED TO BE OFF, SSAO need to be dissabled BEFORE LEVEL IS LOADED.
Enabling SSAO during game play apparently engage/load some functions/shaders that interfere with HDR and dissabling SSAO from this moment doesn't fix HDR! ...Game need to be closed and launched again. Properly set game can be just launched and played without any "every time" manipulation as long as SSGI is dissabled a.k.a for now launched only from launcher, as SSGI is ON by default.
Now i can play...thanks!

Could you provide this in instructions for people to save time, some people may not report and just give up on using this. If you find some time and want to update... those would be best to do:
Set SSAO OFF and block it except from launcher (add info its bugged if used with HDR, force game reload/close-relaunch). Set SSGI OFF except from launcher...this does break things again if i just launch from "Doom3BFG", set anizo x16 as default. Also even more important, launcher does not remember/load its configuration from last run, make it auto-load your saved profile from .cdl file, like when its called CDL.cdl, or set inside launcher path to file to autoload.

Thank You!

**Comment by noabody** [comment]
r_useSSAO 0
r_useSSGI 0
r_useHDR 1

**Comment by RinMaru** [comment]
set use SRGB causes the entire screen to go black so avoide that option

**Comment by RobertBeckebans** [comment]
I cannot reproduce this anymore with the latest master version of RBDOOM-3-BFG.
Please try the prebuilt binaries of RBDOOM-3-BFG 1.2.0 https://github.com/RobertBeckebans/RBDOOM-3-BFG/releases

**Comment by MadDeCoDeR** [comment]
Fine I will upstream RBDOOM-3-BFG as #38 suggested

**Comment by MadDeCoDeR** [comment]
@RobertBeckebans Wow you added support also for the DOOM 3 (2019) Shaders ? Awesome. (Possibly a side effect of the clean up refactor of the rendering code)

**Comment by RobertBeckebans** [comment]
I didn't add support for the DOOM 3 (2019) shaders. 
Actually I don't know anything about that edition :)
However I renamed my shaders from .pixel and .vertex to .hlsl because id really used HLSL language for D3 BFG in those source shaders. Having them included in VS 2017/2019 makes it really easy to edit them and to cross reference functions inside of the HLSL code.

**Comment by MadDeCoDeR** [comment]
@RobertBeckebans I know. That's why I mention that is a possible side effect of your new rendering code

**Comment by MadDeCoDeR** [comment]
Upstreamed version is now live
