### ISSUE TITLE
[Doom 3] Cannot enable SSAO

### ISSUE THREAD

**Issue by Tomle1202** [MadDeCoDeR/Classic-RBDOOM-3-BFG#143]
**Describe the bug**
SSAO auto disables after enabling.

**To Reproduce**
1. All advanced graphic options on, except HDR
2. Set SSAO to enable

**Expected behavior**
SSAO will auto disable itself after enabling.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - CPU: Intel i7 13700
 - GPU: RTX 4070ti
 - Memory: 32GB DDR5
 - GPU: Nvidia 551.23
 - Version: 1.3.1

**Comment by MadDeCoDeR** [comment]
Hi there, this is sadly intended behavior due to SSAO's graphical instability. Sadly until I figure out how to improve it, it will stay that way.

**Comment by Tomle1202** [comment]
Ah I see. That is unfortunate but understandable. Keep up the good work, I hope you'll find a way to fix it soon!
