### ISSUE TITLE
[Doom 3] Extreme slow down and crash upon exiting PDA

### ISSUE THREAD

**Issue by Tomle1202** [MadDeCoDeR/Classic-RBDOOM-3-BFG#144]
**Describe the bug**
FPS drops when exiting the PDA, in one instance it crashed the game.

**To Reproduce**
1. Doom BFA installed correctly, everything working fine
2. Entering the PDA, and then exiting it

**Expected behavior**
The framerate will drop very significantly for 1 second and then come back to normal. This behavior does not always happen but 85% of the time. Very rarely it will also crash the game.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - CPU [Intel i7 13700
 - GPU Nvidia RTX 4070 Ti
 - Memory 32GB DDR5
 - GPU Driver Version Nvidia 551.52
 - Version 1.3.1

**Comment by MadDeCoDeR** [comment]
Hi there, I have some questions about your issue (tried opening and closing the PDA for half an hour and nothing).
Are you using the stable version or the latest nightly build?
What settings have you changed for the game (including key mapping for the PDA)?

**Comment by Tomle1202** [comment]
Hi, I'm using version 1.3.1 and all advanced graphical options are turned on, except for SSAO. Some keys are changed due to gameplay reason but the key for the PDA (Tab) was not touched. 

I should also mention that I have the OpenPlatform (for achievement) installed, but that one is working fine.

**Comment by MadDeCoDeR** [comment]
Hi, have you try the new nightly debug builds?
They can show on console/log OpenGL errors or performance suggestions (if there is any)
