### ISSUE TITLE
Another compile issue on Linux Mint 19.1

### ISSUE THREAD

**Issue by Tsoccerguy3** [MadDeCoDeR/Classic-RBDOOM-3-BFG#15]
see comment here
https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/issues/13#issuecomment-454954163

**Comment by MadDeCoDeR** [comment]
You have installed all the prerequired right?

**Comment by Tsoccerguy3** [comment]
I believe so . all that was pointed out on the opening page . maybe some things are changed with Mint .

**Comment by Tsoccerguy3** [comment]
maybe add some more detail to the instructions would be helpfull . Thank you

**Comment by MadDeCoDeR** [comment]
open the script with the text editor and delete this 
`> /dev/null 2>&1 ||(

echo ERROR Generating files

cd ..

rmdir /Q /S build

read -rsp $'Press any key to continue...\n' -n1 key

)`

And re-run it

**Comment by Tsoccerguy3** [comment]
I think , CMakeLists.txt may not be compatible with Linux Mint or Debian .
may need to add in some checks and handles for Mint or debian

**Comment by MadDeCoDeR** [comment]
Nope, as it seems you are missing the c++ compiler.

**Comment by Tsoccerguy3** [comment]
I built the binary. but i don't think its the right architecture . I get " cannot execute binary file "
I also installed the Game from the Mint Repo , getting the same results . I guess the game is 32 bit and I don't know what 32 bit binaries are missing 
I tried running the original and newly compiled rbdoom3bfg with bash rbdoom3bfg .
do you have a start script to run this and a list of depenencies that need to be installed on a 64 bit version of Mint 19.1 ?

**Comment by MadDeCoDeR** [comment]
The binary is compiled based on the compiler you have installed.
This and the original RBDoom3BFG support both 32-bit and 64-bit on either windows or Linux.
Inside the main source code directory (where the Read Me and Release-notes are) there is a file named RBDoom3BFG open it with a text editor change the directories where is needed and save it as a .desktop file, this will give you a desktop shortcut for the game.

(P.S.: If I am not wrong If you put `:amd64` on the end of a package name it will install the 64bit version)

**Comment by Tsoccerguy3** [comment]
I reinstalled my build environment on Linux Mint 19.1 , and additional pkg

Is this important that i get a error at the end of running the cmakescript . "ERROR Generating files"

GP72-6QF:~/dev/doombfg/neo$ ./cmake-linux-retail.sh
--------------------------------------------------------------------------------
                          CLASSIC RBDOOM 3 BFG EDITION
                     UNIX MakeFile GENERATION FOR x86 - x64
                                  RETAIL BUILD
--------------------------------------------------------------------------------
Generating files
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE_BUILD_TYPE:Retail
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'libavcodec'
--   Found libavcodec, version 57.107.100
-- Checking for module 'libavformat'
--   Found libavformat, version 57.83.100
-- Checking for module 'libavutil'
--   Found libavutil, version 55.78.100
-- Checking for module 'libswscale'
--   Found libswscale, version 4.8.100
-- Checking for module 'libswresample'
--   Found libswresample, version 2.9.100
-- Found FFMPEG or Libav: /usr/lib/x86_64-linux-gnu/libavcodec.so;/usr/lib/x86_64-linux-gnu/libavformat.so;/usr/lib/x86_64-linux-gnu/libavutil.so;/usr/lib/x86_64-linux-gnu/libswscale.so;/usr/lib/x86_64-linux-gnu/libswresample.so, /usr/include/x86_64-linux-gnu
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wds/dev/doombfg/build
ERROR Generating files
GP72-6QF:~/dev/doombfg/neo$

**Comment by MadDeCoDeR** [comment]
Is the build folder still there ?
It's possible you might have deleted wrong lines and it show that error for no reason (and also has no meaning then)
Try to access the build folder and make the binaries, if everything go well then this error is meaningles

**Comment by Tsoccerguy3** [comment]
when running sudo make , i get warning on each of the progress lines during the compile , like the 1 below .
[  6%] Building CXX object idlib/CMakeFiles/idlib.dir/math/MatX.cpp.o
cc1plus: warning: /home/wds/dev/doombfg/neo/idlib/precompiled.h.gch: created and used with different settings of -fpie

**Comment by MadDeCoDeR** [comment]
Don't wory about it.
It just prepairing idLib for the game.so compilation in the end

**Comment by Tsoccerguy3** [comment]
It compiled using original "cmake-linux-retail.sh" with the few warnings .  When running the binary it crashes asking for the default cfg

wds@wds-GP72-6QF:~/dev/doombfg/build$ '/home/wds/Doombfg/rbdoom3bfg.sh'
QA Timing INIT: 000607ms
RBDOOM 3 BFG 1.1.0.1401 linux-amd64
found interface lo - loopback
found interface wlp2s0 - 10.0.9.107/255.255.255.0
------ Initializing File System ------
Current search path:
/home/wds/.rbdoom3bfg/base
/home/wds/Doombfg/base
file system initialized.
--------------------------------------
Sys_Error: Couldn't load default.cfg
wds@wds-GP72-6QF:~/dev/doombfg/build$

**Comment by MadDeCoDeR** [comment]
You HAVE Doom 3 BFG Edition right?

**Comment by Tsoccerguy3** [comment]
yes , the GOG DRM free version

**Comment by MadDeCoDeR** [comment]
Ok, copy paste the RBDoom3BFG file inside the build directory to the game's main directory (not the base directory)

**Comment by Tsoccerguy3** [comment]
ok Thank You , I'll let you know the outcome

**Comment by Tsoccerguy3** [comment]
With your help all is working .Thank You 
Some things that can be added to the opening page
Doom3 BFG DRM free is available on https://www.gog.com/game/doom_3_bfg_edition and so are all the doom games there , DRM free
does not need steam

1.
With the Linux version dropped into the GOG directory , it defaults to Japanese language even though English is set in the GOG version , I needed to remove the Japanese language file from the base / strings directory to make it start in English .

2.
Needs a bash file to start game in Linux Mint . Out of the box Mint does not know what the binary file is .
example

#!/bin/sh
exec ./RBDoom3BFG

3.
Runs fine on a , NTFS , shared windows drive , on a dual boot system .
but for some reason i don't know why the desktop shortcut won't see the game on the NTFS drive 
. I need to run the game from the bash file on the NTFS shared drive . 

4. I hope someone updates and maintains the Linux Mint Repo with a complete solution
