### ISSUE TITLE
All levels can select via main menu 

### ISSUE THREAD

**Issue by Malcolm25-UAC** [MadDeCoDeR/Classic-RBDOOM-3-BFG#154]
Hi, I love your source port, more than rbdoom. You could incorporate the option to choose Level (Scenarios) in the main menu. In order to replay the levels of the game, I know that you have incorporated this in your version https://www.moddb.com/mods/classic-rbdoom-3-bfg-edition/downloads/doom-bfa-version-132-fools -edition. But it would be great if you integrated it along with all the other menu options. Thank you very much for this port, and keep it up.

**Comment by MadDeCoDeR** [comment]
Hi, I won't do that for the standard retail builds. Since they are used also for achievement unlocking, but if you want you can check the Nightly debug builds which have the menu enabled but you can't unlock achievements.

**Comment by MadDeCoDeR** [comment]
Closing issue since it already have been addressed
