### ISSUE TITLE
Classic Doom not playable

### ISSUE THREAD

**Issue by funduke** [MadDeCoDeR/Classic-RBDOOM-3-BFG#16]
**Describe the bug**
I play in Ubuntu Linux the current version Version 1.1.12.5.
In the menue, where i can select either (Ultimate) DooM, DooM 3 or DooM II, ican only enter DooM 3. When i select any of the other two, it beeps and nothing happens. The obviously related message in the terminal is:
DOOM Classic error: W_GetNumForName: STPNNUM2 not found!

Greetings
Funduke

**Comment by MadDeCoDeR** [comment]
Have you updated the newopt.wad ? The updated version is available with the source code you have downloaded in the base\wads directory

**Comment by funduke** [comment]
Oops!
My fault!
It works now fine.
Thank you for the quick reply.

Greetings
Funduke
