### ISSUE TITLE
Vsync doesn't properly match refresh rate

### ISSUE THREAD

**Issue by Keith94** [MadDeCoDeR/Classic-RBDOOM-3-BFG#17]
**To Reproduce**
1. Go to settings
2. Set Vsync to Enabled
3. Set refresh rate to 120 Hz

**Expected behavior**
Vsync should cap the frame rate to refresh rate correctly.

**Actual behavior**
Vsync caps the frame rate at 60 FPS (half the refresh rate)

**Screenshots**
![rbdoom3bfg_2017_08_11_11_17_30_602](https://user-images.githubusercontent.com/5490615/29226630-8e39b412-7e87-11e7-91cd-8c3f1d630d7e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 73

**Additional context**
* Smart Vsync works as intended
* Issue copied from https://github.com/RobertBeckebans/RBDOOM-3-BFG/issues/383

**Comment by MadDeCoDeR** [comment]
Vsync in opengl works as follows: if it is on then it cap the framerate based on monitor refresh rate, if is set to smart (adaptive) then the vsync is closing if the framerate is lower than the monitor's refresh rate.
I hope this clear some things out here.

**Comment by MadDeCoDeR** [comment]
I updated it, and now the framerate is using the monitor refresh rates instead of the original two static values. Hope that makes it better than before

**Comment by Keith94** [comment]
This seems like an improvement. Now I assume someone with a 144 Hz monitor could select it via the "Frame Rate" option.

1. Since it is using the refresh rate, should you rename the option to "Refresh Rate" ?

2. What if someone wanted to set the refresh rate or frame rate limit indecently? Can it be done from the config file?

**Comment by MadDeCoDeR** [comment]
The refresh rate and the frame rate are both now a singular cvar. I won't change the name since it still have the same meaning, and sadly you can't set them up indepenently.

**Comment by Keith94** [comment]
Okay! Thanks
