### ISSUE TITLE
Chaingun fire rate is slower at non-60 FPS frame rates

### ISSUE THREAD

**Issue by Keith94** [MadDeCoDeR/Classic-RBDOOM-3-BFG#18]
**Describe the bug**
Chain gun fires slower when set to 60 FPS or any FPS higher than 120.

**To Reproduce**
1. Go to settings
2. Set frame rate to 60 FPS.
3. Fire chain gun in game

**Expected behavior**
Chain gun fires the same speed as 120 FPS

**Actual behavior**
Chain gun fires slower at 60 FPS or higher than 120 (eg. 240?)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 73

**Additional context**
* https://steamcommunity.com/app/208200/discussions/0/1368380934293336917/

>// To fix the stupid chaingun script that depends on frame counts instead of
// milliseconds in the case of the server running at 60Hz and the client running
// at 120Hz, we need to set the script's GAME_FPS value to the client's effective rate.
// (I'd like to just fix the script to use milliseconds, but we don't want to change assets
// at this point.)

**Comment by MadDeCoDeR** [comment]
That might have been an issue when the refresh rate of the monitor and the framerate of the game are different. Now they are both the same.

**Comment by Keith94** [comment]
I tested the latest build but unfortunately the bug where chain gun fires more slowly on 60 FPS is still present in the game.
