### ISSUE TITLE
the ./cmake-<all varients> just produce the same error

### ISSUE THREAD

**Issue by rstevenson1976** [MadDeCoDeR/Classic-RBDOOM-3-BFG#21]
**Describe the bug**
--------------------------------------------------------------------------------
                                    CLASSIC RBDOOM 3 BFG EDITION
                               UNIX MakeFile GENERATION FOR x86 - x64
                                           RELEASE BUILD
--------------------------------------------------------------------------------
Generating files
./cmake-linux-release.sh: 24: read: Illegal option -s
➜  neo 

**To Reproduce**
1. use any of the cmake options in neo

**Expected behavior**
it producing an executable?

**Screenshots**
being in the terminal, cut and paste should suffice

**Desktop (please complete the following information):**
 - OS: Mint 19.1
 - Browser firefox
 - Version 65.0.1 (64-bit)

**Additional context**
same error on all options

**Comment by MadDeCoDeR** [comment]
The files are generated regularly it's just the "Press any button to continue" message that crashes.
Also these scripts are generating the build files, you must run the compilation by yourself (just go to the build directory open from there the terminal and type make)
