### ISSUE TITLE
only partial game pad usability when accessing pda

### ISSUE THREAD

**Issue by rstevenson1976** [MadDeCoDeR/Classic-RBDOOM-3-BFG#22]
**Describe the bug**
LS and RS do not function when navigating the PDA with an XBox360 gamepad
**To Reproduce**
1. Go to PDA
2. Click on RS or LS on gamepad
3. nothing happens

**Expected behavior**
navigating through the different emails, audio logs, and video disks for any given account on the PDA

**Screenshots**
![screenshot from 2019-03-04 10-01-06](https://user-images.githubusercontent.com/12461190/53741470-79a4b580-3e64-11e9-961a-8af1fe45cd82.png)

**Desktop (please complete the following information):**
 - OS: Mint 19.1
 - Browser Firefox
 - Version 65.0.1 (64-bit)

**Additional context**

**Comment by MadDeCoDeR** [comment]
Does RB/LB work while not on PDA?

**Comment by MadDeCoDeR** [comment]
RS and LS are the Right and Left stick. You are supposed to use them in order to navigate the menus. Last time I check it on my Linux VM they both working quite fine. Closing the issue

**Comment by MadDeCoDeR** [comment]
It's Done. Pull the latest source code and try (not closing it yet

**Comment by MadDeCoDeR** [comment]
Nightly builds are available. If you are still around you can download them and check it
