### ISSUE TITLE
Original flashlight abrupt falloff

### ISSUE THREAD

**Issue by mjsonofharry** [MadDeCoDeR/Classic-RBDOOM-3-BFG#23]
**Describe the bug**
Certain models in the environment interact incorrectly with the original flashlight. These models appear entirely unaffected by the flashlight until the player moves within a certain distance of them, at which point they abruptly light up.

Affected models can include sections of wall, props such as crates, pipes, staircases etc. Floors and terrain tend to not be affected.

**To Reproduce**
1. Create a clean installation by copying _base_ to a new location and extracting Classic RBDOOM 3 on top of it. Ensure that there are no existing RBDOOM 3 profiles with unexpected configurations.
2. Launch Classic RBDOOM 3 with the developer console enabled, set the flashlight to _original_, and load the map _game/mp/d3dm4_ (it can be reproduced in any other map, this is just an easy one to test in)
3. Use the console to give yourself a _weapon_flashlight_
4. Try shining the flashlight on the stack of crates in the large, central room. Walk backwards down the ramp into the hallway while watching the crates.
5. Observe the abrupt transition in the crates from being fully lit by the flashlight to being only lit by environmental lighting.

**Expected behavior**
The crates should gently transition from being fully lit by the flashlight to being only lit by environmental lighting.

**Screenshots**
![lighting](https://user-images.githubusercontent.com/11721593/54798783-9268e580-4c30-11e9-856d-02a94f29f740.gif)

**Desktop**
 - OS: Windows 10 1809 x86_64
 - NVIDIA: 419.35

**Additional context**

I tested and reproduced this in the following versions:
- 1.1.12.9-classic
- 1.1.12.8.5-classic

The problem does not affect the BFG or BFG Mix flashlights. It persists with r_useShadowMapping, r_useHalfLambertLighting, r_useSSAO, r_useHDR, and r_forceambient all set to 0.

Here are the contents of the generated D3BFGConfig.cfg file, sans keybindings:
```
set com_engineHz "60"
set net_inviteOnly "1"
set com_showMemoryUsage "0"
set com_showFPS "0"
set com_requireNonProductionSignIn "1"
set ui_autoReload "1"
set ui_autoSwitch "1"
set ui_skinIndex "0"
set saveGame_verbose "0"
set s_device "-1"
set s_meterPosition "100 100 20 200"
set s_meterTopTime "1000"
set s_showLevelMeter "0"
set g_xp_bind_run_once "1"
set g_gameReviewPause "10"
set g_countDown "15"
set g_fov "80"
set g_gunScale "1"
set g_gunZ "0"
set g_gunY "0"
set g_gunX "3"
set g_showBrass "1"
set g_showProjectilePct "0"
set g_showHud "1"
set g_showPlayerShadow "0"
set g_showcamerainfo "0"
set g_healthTakeLimit "25"
set g_healthTakeAmt "5"
set g_healthTakeTime "5"
set g_useDynamicProtection "1"
set g_armorProtectionMP "0.6"
set g_armorProtection "0.3"
set g_damageScale "1"
set g_leNightmare "0"
set g_roeNightmare "0"
set g_nightmare "0"
set g_decals "1"
set g_bloodEffects "1"
set g_projectileLights "1"
set g_muzzleFlash "1"
set si_flagDropTimeLimit "30"
set si_spectators "1"
set si_teamDamage "0"
set si_timeLimit "10"
set si_fragLimit "10"
set si_mode "-1"
set si_map "-1"
set g_laserSightLength "250"
set g_laserSightWidth "2.0"
set ui_showGun "1"
set g_spectatorChat "0"
set stereoRender_interOccularCentimeters "3.0"
set g_weaponShadows "0"
set g_checkpoints "1"
set aa_targetAimAssistEnable "0"
set pm_cursor "1"
set pm_vmfov "32"
set flashlight_old "1"
set stereoRender_swapEyes "0"
set r_aspectratio "1"
set cl_randpitch "1"
set cl_freelook "0"
set doomit "0"
set cl_messages "1"
set m_show_messages "1"
set s_volume_midi "8"
set s_volume_sound "8"
set net_socksPassword ""
set net_socksUsername ""
set net_socksPort "1080"
set net_socksServer ""
set ui_name ""
set swf_debug "0"
set s_subFraction "0.5"
set s_volume_dB "0"
set stereoRender_warpTargetFraction "1.0"
set stereoRender_warpParmW "0"
set stereoRender_warpParmZ "0"
set stereoRender_warpCenterY "0.5"
set stereoRender_warpCenterX "0.5"
set stereoRender_warpStrength "1.45"
set stereoRender_warp "0"
set r_motionBlur "0"
set r_forceScreenWidthCentimeters "0"
set r_clight "0"
set r_aspectcorrect "0"
set r_aspect "0"
set r_exposure "0.5"
set r_useSSAO "1"
set r_useSSGI "0"
set r_forceAmbient "0.01"
set r_useFilmicPostProcessEffects "1"
set r_hdrAutoExposure "1"
set r_useHDR "1"
set r_shadowMapLodScale "0.4"
set r_useShadowMapping "1"
set r_useVirtualScreenResolution "1"
set stereoRender_deGhost "0.05"
set stereoRender_enable "0"
set r_debugArrowStep "120"
set r_debugLineWidth "1"
set r_debugLineDepthTest "0"
set r_useHalfLambertLighting "1"
set r_lightScale "3"
set r_skipShadows "0"
set r_skipBump "0"
set r_skipSpecular "0"
set r_skipNewAmbient "0"
set r_brightness "1"
set r_gamma "1.0"
set r_swapInterval "1"
set r_lodBias "0.5"
set r_useTrilinearFiltering "1"
set r_maxAnisotropicFiltering "8"
set r_useSRGB "0"
set r_windowHeight "720"
set r_windowWidth "1280"
set r_windowY "0"
set r_windowX "0"
set r_customHeight "720"
set r_customWidth "1280"
set r_fullscreen "0"
set r_vidMode "0"
set r_antiAliasing "0"
set r_displayGLSLCompilerMessages "1"
set m_smooth "1"
set m_yaw "0.022"
set m_pitch "0.022"
set sensitivity "5"
set in_toggleZoom "0"
set in_toggleCrouch "0"
set in_toggleRun "0"
set in_anglespeedkey "1.5"
set in_pitchspeed "140"
set in_yawspeed "140"
set in_joylayout "0"
set in_mouseInvertLook "0"
set in_invertLook "0"
set in_joystickRumble "1"
set in_alwaysRunCl "0"
set in_alwaysRun "1"
set in_mouseSpeed "1"
set joy_deltaPerMSLook "0.003"
set joy_dampenLook "1"
set joy_yawSpeed "240"
set joy_pitchSpeed "100"
set joy_powerScale "2"
set joy_gammaLook "1"
set joy_range "1.0"
set joy_deadZone "0.2"
set joy_triggerThreshold "0.05"
set joy_newCode "1"
set joy_mergedThreshold "1"
set com_preloadDemos "0"
set com_compressDemos "1"
set net_debug_snapShotTime "0"
set com_product_lang_ext "1"
set popupDialog_debug "0"
```

**Comment by MadDeCoDeR** [comment]
To be honest I am as clueless as you are here. I don't know exactly how both flashlights show their lights, but by the look of it, it seems that the old flashlight has a limited illumination distance.

**Comment by mjsonofharry** [comment]
I'm wondering, were you able to replicate the problem? If not, then I was going to try installing everything from scratch on a completely different machine.

**Comment by MadDeCoDeR** [comment]
I did, but the illumination distance was further than this

**Comment by mjsonofharry** [comment]
Try using a _weapon_flashlight.def_ with modified values for **flashTarget**, **flashUp**, and **flashRight**. For example:
```
	"flashTarget"				"0 0 60000"
	"flashUp"				"0 30000 0"
	"flashRight"				"-30000 0 0"
```
Increasing flashTarget has the effect of narrowing the beam while also increasing its range. This seems to either circumvent or control the distance limit we've been observing.

However, it also turns the light into a pinhole. Thus we want to increase flashUp and flashRight as well, so that we get a larger diameter for the light beam.

I am not sure what combination of values would result in a light beam similar to the unmodified one. Also, I don't know exactly how much we need to increase flashTarget in order to cover all plausible viewing distances in all of the game's environments.

**Comment by mjsonofharry** [comment]
Sadly, increasing flashTarget to such a huge value also has the effect of minimizing or even eliminating the flashlight's effect on nearby objects. I wonder if there is a good middle ground.

**Comment by mjsonofharry** [comment]
I have some more information for you. Unless I am mistaken, the original flashlight generates light using the muzzle flash logic, i.e. the flashlight beam is just an extended muzzle flash. I have observed that other muzzle flashes have the same problem. For example, if you pay attention to the light generated when firing the chaingun, you should see a hard edge where the light cuts off, usually visible on the floor. Weapon GUI lights also have hard edges. You can see the chaingun's GUI light cutoff on the view model itself. The plasma gun's GUI light cutoff is only really noticeable if you stand up against a wall because the view model is relatively narrow.

All of this leads me to believe that the problem is related to how the game handles light emitting materials. I don't know how the BFG flashlight works, but my best guess is that it's a different kind of dynamic light.

**Comment by RinMaru** [comment]
looks like this is caused by field of view model. putting it at max causes cut off but putting it at lowest fixes it. unless this is just cause i use BFG Mix

**Comment by MadDeCoDeR** [comment]
> looks like this is caused by field of view model. putting it at max causes cut off but putting it at lowest fixes it. unless this is just cause i use BFG Mix

Nah, BFG Mix only adds battery life to the original flashlight. Nothing too graphical.

**Comment by RinMaru** [comment]
yea then i got it fixed i guess

**Comment by RinMaru** [comment]
ok also tried Original and it is indeed due to **_View Model Field Of View_**
