### ISSUE TITLE
64-bit crashes, 32-bit doesn't

### ISSUE THREAD

**Issue by Blitzoreo** [MadDeCoDeR/Classic-RBDOOM-3-BFG#24]
The 64-bit release (Classic.RBDoom3BFG.-winx64) runs the game but crashes right when selecting Doom 3 BFG. 32-bit release (Classic.RBDoom3BFG.-winx86.zip) has no issues.

I have no idea as to why this happens.
It should work because I have Windows 7 64-bit as my OS.
Maybe the win64x was meant for something else?

**Comment by MadDeCoDeR** [comment]
a. Do you have the game on Steam or GOG ?
b. If you have it on GOG try to close the Steam client and run the game. If that works then delete the OpenPlatformx64.dll from the base folder

**Comment by Blitzoreo** [comment]
I have the GOG version, doing what you suggested did work, but only after I removed OpenPlatformx64.dll, just closing Steam didn't do anything.

**Comment by MadDeCoDeR** [comment]
Ok, just reupload it with the current version of Open Platform. This means that now Open Platform wont gonna cause you any trouble if you don't own the game on Steam.

**Comment by Blitzoreo** [comment]
That worked, the issue is fixed then, thanks!
