### ISSUE TITLE
libavcodec.so.58 missing

### ISSUE THREAD

**Issue by funduke** [MadDeCoDeR/Classic-RBDOOM-3-BFG#27]
**Describe the bug**
I used the downloadable package for Ubuntu Linux (64) and got that error:

./RBDoom3BFG: error while loading shared libraries: libavcodec.so.58: cannot open shared object file: No such file or directory

Greetings
Funduke

**Comment by MadDeCoDeR** [comment]
What version of Ubuntu you are using ? The pre-compiled binary has been compiled in ubuntu 19.
Check if you can download the latest version of FFMPEG (or beta builds)

**Comment by MadDeCoDeR** [comment]
I reinstall my VM with ubuntu 18.04 and rebuild it (with a new fix) I hope now it will be ok (NOTE: if you want to play SIGIL use the compact in Linux due to a bug with EXPINFO)

**Comment by funduke** [comment]
I'm using Ubuntu 18.04.2 LTS. Upon your first recommendation, i updated to 18.10, but then Linux got suck when booting. Then i reinstalled Linux completely, using Ubuntu 19.04, but again Linux stopped during the booting process without offering me the desktop. Then i reinstalled Ubuntu 18.04.2 LTS, and Linux is my friend again! - Well, never change a running system! ...
In the meantime you did some work, thank you for that, and i can play Classic-RBDOOM-3-BFG again. 
I tried it with your precompiled ubuntu64 download version and also by compiling it myself the way, you teached me here: https://www.doomworld.com/forum/post/1884054 . Both make DooM3Bfg play fine.
Running the game this way:
./RBDoom3BFG -file /mods/SIGIL.wad /mods/SIGIL_COMPAT.wad
makes SIGIL play fine as third episode.

Many Thanks, you are doing great work. And many thanks for fixing bugs so quickly!

By the way, the file, that you shared here:
https://www.moddb.com/mods/classic-rbdoom-3-bfg-edition/addons/sigil-bfg
Is not avaiable anymore. I had it, but it got lost, when reinstalling Linux.
