### ISSUE TITLE
Building using clang++ fails

### ISSUE THREAD

**Issue by silviucc** [MadDeCoDeR/Classic-RBDOOM-3-BFG#30]
**Describe the bug**
Trying to compile the latest "stable" release using clang fails

**To Reproduce**
1. Install clang for your distro. In my case it's Fedora: sudo dnf install clang
2. generate the make file with: CXX=/usr/bin/clang++ ./cmake-linux-release.sh
3. change to the build dir and do: make or make -j number_of_cpu_cores
4. This is the output I get is in the attached file. I edited it to change my actual dir with "$HOME"

Attached file:
[clang_output.txt](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/files/3439152/clang_output.txt)

**Desktop (please complete the following information):**
 - OS: Fedora 30

**Comment by MadDeCoDeR** [comment]
I think I have put also some instructions in the wiki. Plus I already accepted your pull request, if the issue is fixed please close the issue.

**Comment by silviucc** [comment]
Hi.
It builds fine with gcc. I was just pointing out that trying to build using clang instead of gcc fails for me.

Thank you for accepting my pull request for the README.txt file.
