### ISSUE TITLE
Strange Green Square when opening PDA

### ISSUE THREAD

**Issue by Lagrotta85** [MadDeCoDeR/Classic-RBDOOM-3-BFG#31]
So, every time I open the PDA in game, the game shows a green square over the PDA while Doomguy in bringing it to his eyesight.
It´s a small flaw, but it doen't happen in RBDoom3, only in RBDoom3 Classic.

**Comment by MadDeCoDeR** [comment]
That's weird. Are you using prebuild binaries of the OG RBDoom ?

**Comment by Lagrotta85** [comment]
I´ve used the 1.1.0-preview3 of RBDoom3 to test.
With this versions I had no issues at all (except for the headless player shadow).

The using the Classic RBDoom 3 BFG version 1.1.12.14 Winx64 version. In this, I get the green square over the PDA. Later today, I will post a sreenshot to ilustrate the issue.

**Comment by Lagrotta85** [comment]
Here are the screenshots.
Strangly, on the screenshots the green Square does not show, but you can see the green tint over Doomguy's hands and PDA.

![rbdoom-3-bfg-20190802-202244-002](https://user-images.githubusercontent.com/53576242/62403671-627a0900-b565-11e9-896f-5bfbd24a5719.jpg)

With OG RBDoom3 this is what I get...
![rbdoom-3-bfg-20190802-203153-001](https://user-images.githubusercontent.com/53576242/62403711-a240f080-b565-11e9-827d-948dbd07d2d8.png)
The green tint is just over the thumbs

**Comment by MadDeCoDeR** [comment]
Go to settings -> advanced settings and lower the player model field of view to the lowest

**Comment by Lagrotta85** [comment]
Tha did it. Thanks!

**Comment by MadDeCoDeR** [comment]
Closing it now. But keeping it in mind for future fix.
