### ISSUE TITLE
Doom I/II config location?

### ISSUE THREAD

**Issue by 2mg** [MadDeCoDeR/Classic-RBDOOM-3-BFG#32]
How do I change keybinds and other cvars for Classic Doom I/II? Is the provided default.cfg shared among all 3 games?

**Comment by MadDeCoDeR** [comment]
The configuration file is shared among all 3 games and usually is in one of the following :
1. Windows : C:\Users\<username>\Saved Games\id Software\RBDOOM 3 BFG\<name of the D3 mod or base>
2. Windows old : C:\Users\<username>\Documents\id Software\RBDOOM 3 BFG\<name of the D3 mod or base>
3.Linux : /home/<username>/.RBDoom3BFG(hidden)/<name of the D3 mod or base>

**Comment by 2mg** [comment]
I see you're saving some Doom I/II cvars in D3BFGConfig.cfg. 

But I'd like to save Gamma Correction 2 and unbind F7 (Quit) since it's close to F6 (Quicksave) - is that possible in config?

**Comment by MadDeCoDeR** [comment]
You can't unbind F-keys (not part of id Tech 5 input), you can press through F11 for Gamma Correction (sorry not saved not a cvar in use here)

**Comment by 2mg** [comment]
Well, at least m_pitch is saved, since Y-axis is double the X-axis speed if using free look, and r_gamma 1.2 is good enough.

Thanks for replying, and please consider adding some sort of F-keys blocking/binding if possible!
