### ISSUE TITLE
"Real Light" behavior?

### ISSUE THREAD

**Issue by 2mg** [MadDeCoDeR/Classic-RBDOOM-3-BFG#33]
While I like what "Real Light" can do, I found some areas literally become either pitch black or extremely dark to the point that you can't recognize the wall/floor texture. Stuff doesn't get a bit lighter even as you approach them.

So I did a quick comparison in Crispy Doom _without_ Crispiness options: https://gfycat.com/absoluteexcellentamericanshorthair

And Classic RBDOOM: https://gfycat.com/highenlightenedadmiralbutterfly

Notice that in Crispy, there is always a radius of gradient lighting. 
Also the stairs I come down and return to in RBDOOM are entirely visible but the floor beneath them is pitch black. 
In Crispy, you know you are in a dark area by design (hard to navigate), while that same area in RBDOOM is pitch black (can't even make what the floor/wall texture is, let alone color).

As I said, I like what "Real Light" can do to a lot of areas, but some are just plain extreme. Tested with SIGIL.wad 1.1 and doom.wad from BFG.

Is this by design?

**Comment by MadDeCoDeR** [comment]
Yes, it is intentional. Real light is meant to make the game look darker and more "atmospheric" which also mean that the gradient light has way higher radius in order to make the lighting in your room to look the same.

**Comment by 2mg** [comment]
Thanks for replying, I appreciate it! I'd like to discuss Real Light a bit more, so bare with me please if you have the time.

> Yes, it is intentional. Real light is meant to make the game look darker and more "atmospheric" gradient light has way higher radius in order to make the lighting in your room to look the same.

But in videos you can see RBDOOM obviously doesn't have a light radius - it's just 3 blocks of black, washed out dark, and completely visible texture/color of floors and walls, there is no in-between, and it won't get even a bit brighter as you approach them.

Compare this section: https://imgur.com/a/1DYzcH1 - I presume (since Crispy's intention is enhanced faithfulness) level designer's intention of that area is to make it VERY dark, but still making you see that you're standing on a bloody floor.
Compare that to Real Light, and you're just in a literally BLACK corridor, and the bloody floor is indiscernible.

So while Real Light can make some areas really more atmospheric, some areas are flat out black and detail-less. Does this make sense (is it really that the intention of Real Light)?

**Comment by MadDeCoDeR** [comment]
Tbh I was just toying around with some light/gamma constants. I guess I can try to re-check them and see if I can keep the atmospheric look but also make dark rooms more visible

**Comment by 2mg** [comment]
Thanks for taking it into consideration. I wasn't sure if current behavior was your intention, the SIGIL expansion, or just my taste. 
Some areas really looked Quake-like with Real Light (like in my videos except where black floor meets bright stairs), but some areas with lava or red blood were pitch black, like that screenshot corridor.

SIGIL expansion is a good way to test it since it has a bunch of dark areas or floors (maybe cross-referencing with Crispy + default Crispiness settings could be a good idea to get an idea which areas are darker by design).
If gamma constants won't work as you intend, consider either adding a bit of light radius around player, or a gradient (opposite of Crispy's cutoff lines seen in screenshot) from bright>less>dim>black.
