### ISSUE TITLE
Crash on selecting video options in classic doom mode

### ISSUE THREAD

**Issue by LordKane1701** [MadDeCoDeR/Classic-RBDOOM-3-BFG#35]
**Describe the bug**
When select "video options" while in classic doom mode, the game crashes. 
**To Reproduce**
1. Start classic doom
2. move to "video options" in options 
3. hit enter 
4. crash.

**Expected behavior**
I expected it to go into video options. 

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Firefox
 - CRBDoom3 1.1.13

**Comment by MadDeCoDeR** [comment]
Oops, I forgot to bundle the new wad. Just reuploaded it with the new wad
