### ISSUE TITLE
Re-implement pk4 support

### ISSUE THREAD

**Issue by RinMaru** [MadDeCoDeR/Classic-RBDOOM-3-BFG#36]
One thing that has to be really annoying is the need for texture packs to be extracted and take up allot of space is it possible to implement some sort of zipped or package support?

**Comment by MadDeCoDeR** [comment]
Well, after the first play any texture and models the game used are getting binarized (lower size and faster to load) after that the original is no longer needed.
As for a support for a compressed format, I guess I will to look into it at some point. (But no promises)

**Comment by RinMaru** [comment]
yea thats the problem like hi def is 4gb compressed but is 14gb extracted and since the game does the generated texture thing having a compressed format would be great

**Comment by RinMaru** [comment]
I see something going on lol are resource files compressed? and how would i go about using this? 

this is the HiDef mod folder
![Annotation 2019-09-14 061606](https://user-images.githubusercontent.com/15071652/64906666-449cd980-d6b7-11e9-99af-17cd75a7705e.jpg)

**Comment by MadDeCoDeR** [comment]
Check the wiki for full instructions: https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/wiki

**Comment by MadDeCoDeR** [comment]
Also here is an example https://www.moddb.com/mods/classic-rbdoom-3-bfg-edition/addons/classic-doom-3-bfg-edition (extract the resources file in order to see what it has)

**Comment by RinMaru** [comment]
so this will make a single resource file out of the generated folder? im just not sure how to work the console and how i would type the command

**Comment by MadDeCoDeR** [comment]
It will make a resource file out of a mod folder (which can have the generated folder). Did you ever try to cheat in Doom 3 BFG ? (It's not a shame to admit it) Because if you have then there isn't much to tell you about using the console

**Comment by RinMaru** [comment]
not really only thing ive done in console was exec a config file. i figured out how to do it lol just a shame the resource files arnt compressed

**Comment by MadDeCoDeR** [comment]
Yeah that's Why in the instruction I said to keep the generated files for the .resource and not the original.
Generated = binarized = less space

**Comment by RinMaru** [comment]
or i can use windows compact. having them in resource files seems to speed up loading

**Comment by MadDeCoDeR** [comment]
The original files are not needed inside the .resource file. Hence they might even ignored

**Comment by RinMaru** [comment]
well i tried making a resource out of the generated folder and none of the textures loaded in all just vanilla textures

**Comment by MadDeCoDeR** [comment]
If you load the folder itself as a mod will it work ?

**Comment by RinMaru** [comment]
didnt test ill have to try it

**Comment by MadDeCoDeR** [comment]
is the folder you are using to make the .resource ?

**Comment by RinMaru** [comment]
i moved the generated into the root folder then after converting it to resource i put it back into the folder it would be in

**Comment by MadDeCoDeR** [comment]
Just copy the folder of the mod and just remove the files I describe on the wiki and convert THAT folder to a .resource

**Comment by RinMaru** [comment]
@baseHD is what i moved the generated resource file back into you can see thats where the hi def mod is at in the screenshot

**Comment by MadDeCoDeR** [comment]
How large is the file ? (It must be ~1GB, if it is more then you should move files to new folders in order to have each file to be < 1GB)

**Comment by RinMaru** [comment]
the intire mod is 11gb ive made sure the files dont go over 4gb is 4gb too much?

**Comment by MadDeCoDeR** [comment]
Yes, anything close to 4GB is bad as I recommend each file must be < 1GB (Plus if you are doing this for Hi-Def I can give you mine version which works is only 4GB with 7 .resource files)

**Comment by RinMaru** [comment]
is it the latest version 3.1j if so then yea that would be great lol

**Comment by MadDeCoDeR** [comment]
Yes, it is https://1drv.ms/u/s!ApXxGWdXfXvNyQCL-IJ8yu4hBiX0?e=vXqrxv (sorry for the late response but it took me some time to upload it)

**Comment by RinMaru** [comment]
thanks allot lol ^^

**Comment by RinMaru** [comment]
im having a problem its not loading the textures

**Comment by MadDeCoDeR** [comment]
Are you sure ? TBH I can barely notice the difference, I noticed through that the shotgun is having a woodgrain handle which is loading fine with these resources

**Comment by RinMaru** [comment]
yea its not loading its all just vanilla assets

**Comment by MadDeCoDeR** [comment]
Neither the shotgun textures?

**Comment by RinMaru** [comment]
I didnt play that far i noticed stuff wasnt loaded right off the bat

**Comment by MadDeCoDeR** [comment]
And just found the issue just download the new binaries and try again (some bugs and glitches are expected)

**Comment by RinMaru** [comment]
alright will do

**Comment by MadDeCoDeR** [comment]
Well as it turn out Hi-Def had it's own generated files (who knew right?) anyway I repackage everything from (near) scratch and here it is https://www.moddb.com/mods/classic-rbdoom-3-bfg-edition/addons/doom-3-bfg-hi-def-resource-edition

**Comment by RinMaru** [comment]
oh how did you get the size down?

**Comment by RinMaru** [comment]
![IMG_20190917_202853_hdr](https://user-images.githubusercontent.com/15071652/65089116-f115de80-d989-11e9-823a-e1e1e359591b.jpg)
heres how it should look

**Comment by MadDeCoDeR** [comment]
Yep that is expected. I guess I can try to fix it later on (just have to rename the folders with the buggy models and change their defs)

**Comment by RinMaru** [comment]
i wonder why they broke in resource form

**Comment by MadDeCoDeR** [comment]
Possibly it is loading additional vanilla files that mess them up

**Comment by RinMaru** [comment]
alright then if you have any builds i should test ill keep a lookout

**Comment by MadDeCoDeR** [comment]
And just updated it now only the shotgun and pistol world models are messed up

**Comment by RinMaru** [comment]
hmm same reason the other model messed up?

**Comment by MadDeCoDeR** [comment]
Possibly, but Hi-Def doesn't seems to have the needed files in order to fix that. :(

**Comment by RinMaru** [comment]
shame that y2keeth isnt working on it anymore.

**Comment by RinMaru** [comment]
id love to help you out with managing the HiDef mod and figuring some stuff out is there anything i can do? im not really skilled with this stuff but i can view the textures.

**Comment by MadDeCoDeR** [comment]
Well, you can start by checking the files of the original Hi-Def, also you can use "extractresourcefile" command to see what files the .resources I made is having. 

P.S. : The real issue is probably with the model texture mapping,

**Comment by RinMaru** [comment]
ill try that. is it possible that some stuff just doesnt get put into generated folder and is always read from the folders?

**Comment by MadDeCoDeR** [comment]
It shouldn't but it is possible.

**Comment by RinMaru** [comment]
im having a bit of trouble unpacking the resources can you possibly send a unpacked zip?

**Comment by MadDeCoDeR** [comment]
What problem ? Try "extractresourcefile HiDef1.resources base/HiDef1" for example

**Comment by RinMaru** [comment]
ah ok.

**Comment by MadDeCoDeR** [comment]
For **Env** and **Lights** check the _**generated/images**_ for models they are pretty much all over the generated folder in _**models**_ _**rendermodels**_ _**collision**_ and _**images/models**_

**Comment by RinMaru** [comment]
doesnt seem all of lights and env were moved over unless files were merged when generated

**Comment by RinMaru** [comment]
did you find out anything on the basedev folder?

**Comment by MadDeCoDeR** [comment]
Only what the basedev folder is stand for. Development resources for modders.

**Comment by RinMaru** [comment]
so no idea if it serves a purpose with the Hidef mod itself?

**Comment by RinMaru** [comment]
i guess this can be closed since the other issues are unrelated to this
