### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by blushingpenguin** [MadDeCoDeR/Classic-RBDOOM-3-BFG#37]
I get an access violation on startup with the released download on win64.  I have tried recompiling the code to track this down, currently I get:

glConfig.version_string = ( const char* )glGetString( GL_VERSION );

returning NULL, which makes float glVersion = atof( glConfig.version_string ); throw an assertion (which might be the access violation in release mode).

It looks like opengl might need some setup before it is used, I had a stab but didn't get anywhere.  Any pointers would be great, seems like I'm missing something obvious here.

**Comment by MadDeCoDeR** [comment]
Specs ? drivers installed ?

**Comment by blushingpenguin** [comment]
I'm using a mobile NVIDIA RTX 2080 with the current (436.15) drivers on Win10 x64

**Comment by MadDeCoDeR** [comment]
what version of OpenGL the driver says it has ?

**Comment by blushingpenguin** [comment]
vanilla works ok (current steam version -- alt-tab is bust but the game plays ok)

http://realtech-vr.com/admin/glview reports the opengl version as Version: 4.6.0 NVIDIA 436.15

glConfig.version_string = ( const char* )glGetString( GL_VERSION );
returns NULL in the debugger

**Comment by MadDeCoDeR** [comment]
What exactly the console shows ?

**Comment by blushingpenguin** [comment]
if you mean the inbuilt console, it doesn't get that far. if you mean the windows equivalent, it doesn't show anything, just records the av as an event record:

Faulting application name: RBDoom3BFG.exe, version: 1.0.0.1, time stamp: 0x5d60c89b
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process ID: 0x2d58
Faulting application start time: 0x01d56687d17f3a1d
Faulting application path: C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\RBDoom3BFG.exe
Faulting module path: unknown
Report ID: 0474f228-80e1-48a4-be44-2fae31185a67
Faulting package full name: 
Faulting package-relative application ID:

**Comment by MadDeCoDeR** [comment]
The inbuilt. It can help to find the issue faster

**Comment by blushingpenguin** [comment]
ok, looks like it dumps to the debugger, I didn't notice that before:

'RBDoom3BFG.exe' (Win32): Loaded 'C:\dev\Classic-RBDOOM-3-BFG\buildALx64\Debug\RBDoom3BFG.exe'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\dinput8.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\opengl32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\xinput1_3.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Unloaded 'C:\Windows\System32\msvcrt.dll'
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Unloaded 'C:\Windows\System32\ucrtbase.dll'
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\IPHLPAPI.DLL'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Unloaded 'C:\Windows\System32\cfgmgr32.dll'
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\wsock32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\OpenAL32.dll'. Module was built without symbols.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\avcodec-58.dll'. Module was built without symbols.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\avformat-58.dll'. Module was built without symbols.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Unloaded 'C:\Windows\System32\ole32.dll'
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\umpdc.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\avutil-56.dll'. Module was built without symbols.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\swscale-5.dll'. Module was built without symbols.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\glu32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\swresample-3.dll'. Module was built without symbols.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\winmmbase.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'RBDoom3BFG.exe' (Win32): Unloaded 'C:\Windows\System32\winmmbase.dll'
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ncrypt.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ntasn1.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\ProgramData\A-Volute\DellInc.AlienwareSoundCenter\Modules\ScheduledModules\x64\DellInc.AlienwareSoundCenterDevProps2.dll'. 
'RBDoom3BFG.exe' (Win32): Loaded 'C:\ProgramData\A-Volute\DellInc.AlienwareSoundCenter\Modules\ScheduledModules\x64\CassiniMLKOSD.dll'. 
'RBDoom3BFG.exe' (Win32): Loaded 'C:\ProgramData\A-Volute\DellInc.AlienwareSoundCenter\Modules\ScheduledModules\x64\ProductInfo.Dll'. 
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.18362.295_none_e6c3acbd13101292\comctl32.dll'. Symbols loaded.
QA Timing INIT: 000002ms
Classic RBDOOM 3 BFG 1.1.13.1403-debug win-x64 Sep  8 2019 20:13:45
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\sspicli.dll'. Symbols loaded.
3600 MHz generic CPU with SSE & SSE2
Winsock Initialized
Found interface: {16B2DCF4-4B9F-4AA3-B8DE-832C4FCD16B2} Bluetooth Device (Personal Area Network) - 0.0.0.0 NULL netmask - skipped
Found interface: {40D5B968-7949-4ADA-94DC-8FD87261A319} Killer E3000 2.5 Gigabit Ethernet Controller - 10.0.5.53/255.255.255.0
Found interface: {932A6861-43EE-40A1-B8A3-BA1A03D28C52} Hyper-V Virtual Ethernet Adapter - 172.17.228.65/255.255.255.240
Found interface: {4A13E00B-A416-47E5-90C2-F005FD594EF1} Hyper-V Virtual Ethernet Adapter #2 - 10.0.5.40/255.255.255.0
Found interface: {D34249D0-9DE0-4EDE-BD6A-E5730190D3B8} Npcap Loopback Adapter - 169.254.144.152/255.255.0.0
Found interface: {DD7A9707-D3EB-4253-B46B-7ABD0F65CB39} Hyper-V Virtual Ethernet Adapter #3 - 10.0.75.1/255.255.255.240
Found interface: {FD18C70D-59F6-438B-AB96-6C8070C28941} Killer(R) Wireless-AC 1550 Wireless Network Adapter (9260NGW) 160MHz - 10.0.5.48/255.255.255.0
Found interface: {A53AFCD2-0A75-4180-B2A9-3E2B1A229D45} Microsoft Wi-Fi Direct Virtual Adapter - 0.0.0.0 NULL netmask - skipped
Found interface: {96046CE9-7F40-4DFA-8D95-755CB6FE2E5F} Microsoft Wi-Fi Direct Virtual Adapter #2 - 0.0.0.0 NULL netmask - skipped
Sys_InitNetworking: adding loopback interface
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\nsi.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\iertutil.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. Symbols loaded.
------ Initializing File System ------
Loaded resource file _common.resources
Loaded resource file _ordered.resources
Loaded resource file _sound_pc.resources
Loaded resource file _sound_pc_en.resources
Loaded resource file maps/admin.resources
Loaded resource file maps/alphalabs1.resources
Loaded resource file maps/alphalabs2.resources
Loaded resource file maps/alphalabs3.resources
Loaded resource file maps/alphalabs4.resources
Loaded resource file maps/caverns1.resources
Loaded resource file maps/caverns2.resources
Loaded resource file maps/comm1.resources
Loaded resource file maps/commoutside.resources
Loaded resource file maps/cpu.resources
Loaded resource file maps/cpuboss.resources
Loaded resource file maps/d3ctf1.resources
Loaded resource file maps/d3ctf2.resources
Loaded resource file maps/d3ctf3.resources
Loaded resource file maps/d3ctf4.resources
Loaded resource file maps/d3dm1.resources
Loaded resource file maps/d3dm2.resources
Loaded resource file maps/d3dm3.resources
Loaded resource file maps/d3dm4.resources
Loaded resource file maps/d3dm5.resources
Loaded resource file maps/d3xpdm1.resources
Loaded resource file maps/d3xpdm2.resources
Loaded resource file maps/d3xpdm3.resources
Loaded resource file maps/d3xpdm4.resources
Loaded resource file maps/delta1.resources
Loaded resource file maps/delta2a.resources
Loaded resource file maps/delta2b.resources
Loaded resource file maps/delta3.resources
Loaded resource file maps/delta4.resources
Loaded resource file maps/delta5.resources
Loaded resource file maps/deltax.resources
Loaded resource file maps/enpro.resources
Loaded resource file maps/erebus1.resources
Loaded resource file maps/erebus2.resources
Loaded resource file maps/erebus3.resources
Loaded resource file maps/erebus4.resources
Loaded resource file maps/erebus5.resources
Loaded resource file maps/erebus6.resources
Loaded resource file maps/hell.resources
Loaded resource file maps/hell1.resources
Loaded resource file maps/hellhole.resources
Loaded resource file maps/le_enpro1.resources
Loaded resource file maps/le_enpro2.resources
Loaded resource file maps/le_exis1.resources
Loaded resource file maps/le_exis2.resources
Loaded resource file maps/le_hell.resources
Loaded resource file maps/le_hell_post.resources
Loaded resource file maps/le_underground.resources
Loaded resource file maps/le_underground2.resources
Loaded resource file maps/mars_city1.resources
Loaded resource file maps/mars_city2.resources
Loaded resource file maps/mc_underground.resources
Loaded resource file maps/monorail.resources
Loaded resource file maps/phobos1.resources
Loaded resource file maps/phobos2.resources
Loaded resource file maps/phobos3.resources
Loaded resource file maps/phobos4.resources
Loaded resource file maps/recycling1.resources
Loaded resource file maps/recycling2.resources
Loaded resource file maps/site3.resources
Current search path:
C:\Users\mark\Saved Games\id Software\RBDOOM 3 BFG/base
C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition/base
_common.resources
_ordered.resources
_sound_pc.resources
_sound_pc_en.resources
maps/admin.resources
maps/alphalabs1.resources
maps/alphalabs2.resources
maps/alphalabs3.resources
maps/alphalabs4.resources
maps/caverns1.resources
maps/caverns2.resources
maps/comm1.resources
maps/commoutside.resources
maps/cpu.resources
maps/cpuboss.resources
maps/d3ctf1.resources
maps/d3ctf2.resources
maps/d3ctf3.resources
maps/d3ctf4.resources
maps/d3dm1.resources
maps/d3dm2.resources
maps/d3dm3.resources
maps/d3dm4.resources
maps/d3dm5.resources
maps/d3xpdm1.resources
maps/d3xpdm2.resources
maps/d3xpdm3.resources
maps/d3xpdm4.resources
maps/delta1.resources
maps/delta2a.resources
maps/delta2b.resources
maps/delta3.resources
maps/delta4.resources
maps/delta5.resources
maps/deltax.resources
maps/enpro.resources
maps/erebus1.resources
maps/erebus2.resources
maps/erebus3.resources
maps/erebus4.resources
maps/erebus5.resources
maps/erebus6.resources
maps/hell.resources
maps/hell1.resources
maps/hellhole.resources
maps/le_enpro1.resources
maps/le_enpro2.resources
maps/le_exis1.resources
maps/le_exis2.resources
maps/le_hell.resources
maps/le_hell_post.resources
maps/le_underground.resources
maps/le_underground2.resources
maps/mars_city1.resources
maps/mars_city2.resources
maps/mc_underground.resources
maps/monorail.resources
maps/phobos1.resources
maps/phobos2.resources
maps/phobos3.resources
maps/phobos4.resources
maps/recycling1.resources
maps/recycling2.resources
maps/site3.resources
file system initialized.
--------------------------------------
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
execing default.cfg
couldn't exec D3BFGConfig.cfg
couldn't exec autoexec.cfg
Initializing Platform
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\base\OpenPlatformx64.dll'. Module was built without symbols.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamapps\common\DOOM 3 BFG Edition\steam_api64.dll'. 
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\steamclient64.dll'. 
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\psapi.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\vstdlib_s64.dll'. 
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\tier0_s64.dll'. 
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\secur32.dll'. Symbols loaded.
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Program Files (x86)\Steam\GameOverlayRenderer64.dll'. 
Platform loaded sucessfully !!!
----- R_InitOpenGL -----
r_fullscreen reset from 1 to 1 because mode list failed.Going to safe mode because mode list failed.r_fullscreen reset from 1 to 1 because mode list failed.Going to safe mode because mode list failed.
------- Input Initialization -------
Initializing DirectInput...
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\hid.dll'. Symbols loaded.
mouse: Couldn't set DI coop level
------------------------------------
Debug Assertion Failed!

Program: C:\dev\Classic-RBDOOM-3-BFG\buildALx64\Debug\RBDoom3BFG.exe
File: minkernel\crts\ucrt\src\appcrt\convert\atof.cpp
Line: 65

Expression: string != nullptr

For information on how your program can cause an assertion
failure, see the Visual C++ documentation on asserts.

(Press Retry to debug the application)
'RBDoom3BFG.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. Symbols loaded.
The thread 0x8e7c has exited with code 3 (0x3).
The thread 0x4c58 has exited with code 3 (0x3).
The thread 0x6c98 has exited with code 3 (0x3).
The thread 0x13cc has exited with code 3 (0x3).
The thread 0x74ac has exited with code 3 (0x3).
The thread 0x6a98 has exited with code 3 (0x3).
The thread 0x48e8 has exited with code 3 (0x3).
The thread 0x59b0 has exited with code 3 (0x3).
The thread 0x5120 has exited with code 3 (0x3).
The thread 0x4f98 has exited with code 3 (0x3).
The program '[0x87C0] RBDoom3BFG.exe' has exited with code 3 (0x3).

**Comment by MadDeCoDeR** [comment]
Try +set r_fullscreen 0

**Comment by blushingpenguin** [comment]
yep, that makes it start
