### ISSUE TITLE
Rebase on upstream RBDOOM-3-BFG

### ISSUE THREAD

**Issue by Danfun64** [MadDeCoDeR/Classic-RBDOOM-3-BFG#38]
https://github.com/RobertBeckebans/RBDOOM-3-BFG and your fork have diverged years ago. Granted, your fork has added much more than the original, but the original still has some bugfixes and improvements that your fork is missing.

I'd like to request that you rebase your fork so that it also reflects the latest original RBDOOM-3-BFG code.

**Comment by MadDeCoDeR** [comment]
Many of these updates are maintanse updated that are already implemented in this version

**Comment by Danfun64** [comment]
Perhaps. If anything, it makes the code harder to follow. I imagine some of the comments that port things over to your fork are redundant compared with upstream.

It appears that the last commits on both your fork and upstream that match are https://github.com/RobertBeckebans/RBDOOM-3-BFG/commit/80df3182f1db17c282306f4095a75637db86f484 / https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/commit/80df3182f1db17c282306f4095a75637db86f484

I would have thought that it would've been good practice to directly base your fork on upstream.

Among the commits your fork is missing is the contents of the pull request at https://github.com/RobertBeckebans/RBDOOM-3-BFG/pull/432 ...

**Comment by MadDeCoDeR** [comment]
Done
