### ISSUE TITLE
Compile error on Ubuntu 18.04

### ISSUE THREAD

**Issue by funduke** [MadDeCoDeR/Classic-RBDOOM-3-BFG#40]
Hello!
I've got a compile error on Ubuntu 18.04:

funduke@doomsday:~/Classic-RBDOOM-3-BFG/neo$  ./cmake-linux-retail.sh 

--------------------------------------------------------------------------------
                                DOOM BFA EDITION
                     UNIX MakeFile GENERATION FOR x86 - x64
                                  RETAIL BUILD
--------------------------------------------------------------------------------
Generating files
Files generated Successfully
funduke@doomsday:~/Classic-RBDOOM-3-BFG/neo$  cd .. 
funduke@doomsday:~/Classic-RBDOOM-3-BFG$  cd build 
funduke@doomsday:~/Classic-RBDOOM-3-BFG/build$ make
Scanning dependencies of target precomp_header_idlib
[  0%] Creating idlib/precompiled.h.gch for idlib
In file included from precompiled.h:36:0:
sys/sys_types.h:98:2: error: ‘constexpr’ does not name a type
  constexpr idNullPtr() : value( 0 ) { }
  ^
sys/sys_types.h:98:2: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
sys/sys_types.h:101:24: error: ‘constexpr’ does not name a type
  template<typename T1> constexpr operator T1* () const
                        ^
sys/sys_types.h:101:24: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
sys/sys_types.h:107:37: error: ‘constexpr’ does not name a type
  template<typename T1, typename T2> constexpr operator T1 T2::* () const
                                     ^
sys/sys_types.h:107:37: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
idlib/CMakeFiles/precomp_header_idlib.dir/build.make:57: recipe for target 'idlib/CMakeFiles/precomp_header_idlib' failed
make[2]: *** [idlib/CMakeFiles/precomp_header_idlib] Error 1
CMakeFiles/Makefile2:199: recipe for target 'idlib/CMakeFiles/precomp_header_idlib.dir/all' failed
make[1]: *** [idlib/CMakeFiles/precomp_header_idlib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
funduke@doomsday:~/Classic-RBDOOM-3-BFG/build$

**Comment by MadDeCoDeR** [comment]
Just updated the cmake script to enforce the c++11 standard (require CMake 3.1or later).
Also why you don't try the prebuilt binary? Doesn't work ?

**Comment by funduke** [comment]
Trying the precompiled binary with the command ./DoomBFA.sh results with the message

funduke@doomsday:~/Downloads/doom/DOOMBFA$ nohup: hänge Ausgabe an 'nohup.out' an

but the nohup.out remains to be an empty file.
But the game does not start.

Trying to run the precompiled version with ./DoomBFA results in the message:

Ungültiger Maschinenbefehl (Speicherabzug geschrieben)

And the game also does not start.


So i tried it again with 'make' on the updated source files from the git repository.
The result was exactly like the above.
Then i installed explicitly cmake with this command:

sudo apt-get install cmake cmake-qt-gui 

and checked the cmake version. It is:
cmake version 3.10.2

Then i tried again to build the executable. The make output was the following:


funduke@doomsday:~/Classic-RBDOOM-3-BFG/build$ make
Scanning dependencies of target precomp_header_idlib
[  0%] Creating idlib/precompiled.h.gch for idlib
In file included from precompiled.h:36:0:
sys/sys_types.h:98:2: error: ‘constexpr’ does not name a type
  constexpr idNullPtr() : value( 0 ) { }
  ^
sys/sys_types.h:98:2: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
sys/sys_types.h:101:24: error: ‘constexpr’ does not name a type
  template<typename T1> constexpr operator T1* () const
                        ^
sys/sys_types.h:101:24: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
sys/sys_types.h:107:37: error: ‘constexpr’ does not name a type
  template<typename T1, typename T2> constexpr operator T1 T2::* () const
                                     ^
sys/sys_types.h:107:37: note: C++11 ‘constexpr’ only available with -std=c++11 or -std=gnu++11
idlib/CMakeFiles/precomp_header_idlib.dir/build.make:57: recipe for target 'idlib/CMakeFiles/precomp_header_idlib' failed
make[2]: *** [idlib/CMakeFiles/precomp_header_idlib] Error 1
CMakeFiles/Makefile2:199: recipe for target 'idlib/CMakeFiles/precomp_header_idlib.dir/all' failed
make[1]: *** [idlib/CMakeFiles/precomp_header_idlib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MadDeCoDeR** [comment]
A. try the command g++ --version (on my VM which is also Ubuntu 18.04 it is 7.4)
B. Can you try with the previous version ? (the only difference is the new name but still)

**Comment by funduke** [comment]
The compiler version was too low on my system and it refused to be updated. So i reinstalled Ubuntu and now i was able to compile a playable executable from github. I'm happy :)
The precompiled binary version stays unplayable by the way, but is, at least for me now, no problem.
