### ISSUE TITLE
Game Crashes On Loading Screen When Playing Doom 3 With This Mod

### ISSUE THREAD

**Issue by Robin613507** [MadDeCoDeR/Classic-RBDOOM-3-BFG#43]
The Game Crashes On Loading Screen At The End Of The Intro Text Here Is The Qconsole

log file 'qconsole.log' opened on Wed Feb 26 14:26:05 2020

]sv_cheats 1
Unknown command 'sv_cheats'
]set logfile 1
NET: PartyToken is 258 (seed = 273413)
--------- Execute Map Change ---------
Map: game/mars_city1
Loaded resource file maps/mars_city1.resources
--------- Game Map Shutdown ----------
WARNING: idSessionLocal::Pump was not called for 4 seconds
WARNING: idSessionLocal::Pump was not called for 4 seconds
WARNING: idSessionLocal::Pump was not called for 4 seconds
--------------------------------------
 18315 msec to unload map
    47 msec to free assets
Preloading images...
02180 images preloaded ( or were already loaded ) in   8.5 seconds
----------------------------------------
WARNING: idSessionLocal::Pump was not called for 13 seconds
00305 models preloaded ( or were already loaded ) in   0.8 seconds
----------------------------------------
OpenAL Error: Invalid Name (0xa001), @ D:\repos\Classic-RBDOOM-3-BFG\neo\sound\OpenAL\AL_SoundSample.cpp 748
00551 sounds preloaded in   6.0 seconds
----------------------------------------
Preloading anims...
00630 anims preloaded ( or were already loaded ) in   6.9 seconds
----------------------------------------
WARNING: idSessionLocal::Pump was not called for 16 seconds
----------- Game Map Init ------------
collision data:
   425 models
 30834 vertices (722 KB)
 54572 edges (1918 KB)
 44488 polygons (3126 KB)
  8144 brushes (1113 KB)
 12573 nodes (343 KB)
 43839 polygon refs (342 KB)
 14455 brush refs (112 KB)
 18344 internal edges
  1463 sharp edges
     0 contained polygons removed
     0 polygons merged
  7681 KB total memory used
124 msec to load collision data.
Preloading collision models...
00183 collision models preloaded ( or were already loaded ) in   0.2 seconds
----------------------------------------
map bounds are (19640.0, 22168.0, 29496.0)
max clip sector is (1227.5, 1385.5, 1843.5)
    2 KB passage memory used to build PVS
   35 msec to calculate PVS
   56 areas
  110 portals
    9 areas visible on average
  448 bytes PVS data
[Load AAS]
loading maps/game/mars_city1.aas48
done.
[Load AAS]
loading maps/game/mars_city1.aas96
[Load AAS]
loading maps/game/mars_city1.aas_guardian
[Load AAS]
loading maps/game/mars_city1.aas_mancubus
[Load AAS]
loading maps/game/mars_city1.aas_sabaoth
[Load AAS]
loading maps/game/mars_city1.aas_cyberdemon
Entering doom_main()
Exiting doom_main()
Spawning entities
WARNING: marscity_cinematic_sarge_1 has no AAS file
WARNING: marscity_cinematic_sarge2_1 has no AAS file
WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/dropship.bik', 0

Loaded FFMPEG file: 'video/marscity/dropship.bik', looping=0256x256, 31.250000 FPS, 1.704000 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/monoflyby.bik', 0

Loaded FFMPEG file: 'video/marscity/monoflyby.bik', looping=0256x256, 31.250000 FPS, 0.672000 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/ship.bik', 0

Loaded FFMPEG file: 'video/marscity/ship.bik', looping=0256x256, 30.000000 FPS, 4.733333 sec
WARNING: idCinematic: Cannot find an audio stream in: 'sound/VO/video/video_uac_welcome.bik', 0

Loaded FFMPEG file: 'sound/VO/video/video_uac_welcome.bik', looping=0256x256, 30.000000 FPS, 80.366669 sec
WARNING: marscity_cinematic_player_sarge has no AAS file
WARNING: idCinematic: Cannot find an audio stream in: 'sound/VO/video/video_ipn_news.bik', 0

Loaded FFMPEG file: 'sound/VO/video/video_ipn_news.bik', looping=0256x256, 30.000000 FPS, 187.433334 sec
WARNING: idCinematic: Cannot find an audio stream in: 'sound/VO/video/video_marine_sops.bik', 0

Loaded FFMPEG file: 'sound/VO/video/video_marine_sops.bik', looping=0256x256, 30.000000 FPS, 72.866669 sec
WARNING: idCinematic: Cannot find an audio stream in: 'sound/VO/video/video_plasmagun.bik', 0

Loaded FFMPEG file: 'sound/VO/video/video_plasmagun.bik', looping=0256x256, 30.000000 FPS, 47.833332 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/decom.bik', 1

Loaded FFMPEG file: 'video/marscity/decom.bik', looping=1128x128, 30.000000 FPS, 4.266667 sec
WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/sci_team_request.bik', 0

Loaded FFMPEG file: 'video/marscity/sci_team_request.bik', looping=0256x256, 30.000000 FPS, 8.833333 sec
WARNING: idCinematic: Cannot find an audio stream in: 'sound/vo/video/mfs.bik', 0

Loaded FFMPEG file: 'sound/vo/video/mfs.bik', looping=0256x256, 30.000000 FPS, 88.833336 sec
...2026 entities spawned, 0 inhibited

==== Processing events ====
client 0 connected.
SpawnPlayer: 0
DESKTOP-CJLSLMQ joined the game.
--------------------------------------
Sending networkSync cvars:
pm_staminathreshold = 4
pm_noclipspeed = 300
pm_runspeed = 275
pm_walkspeed = 175
pm_crouchspeed = 100
WARNING: idClipModel::Handle: clip model 0 on 'marscity_soldier_black_2_head' (102) is not a collision or trace model
----- idRenderModelManagerLocal::EndLevelLoad -----
    0 models purged from previous level,  1037 models kept.
---------------------------------------------------
----- idImageManager::EndLevelLoad -----
WARNING: Couldn't load image: _emptyname : _emptyname#__0200
 2163 images loaded in  23.2 seconds
----------------------------------------
----- idSoundSystemLocal::EndLevelLoad -----
sound: found efxs/mars_city1.efx
  161 sounds loaded in   2.8 seconds
----------------------------------------
----- Running initial game frames -----
----- Saving Game -----
Save time: 1191ms
----- Generating Interactions -----
WARNING: idSessionLocal::Pump was not called for 3 seconds
idRenderWorld::GenerateAllInteractions, msec = 513
interactionTable size: 2952636 bytes
30576 interactions take 1100736 bytes
Used 14044kb of static vertex memory (22%)
Used 4730kb of static index memory (14%)
------------- Warnings ---------------
during game/mars_city1...
WARNING: idSessionLocal::Pump was not called for 16 seconds
WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/dropship.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/monoflyby.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/ship.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'sound/VO/video/video_uac_welcome.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'sound/VO/video/video_ipn_news.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'sound/VO/video/video_marine_sops.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'sound/VO/video/video_plasmagun.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/decom.bik', 1

WARNING: idCinematic: Cannot find an audio stream in: 'video/marscity/sci_team_request.bik', 0

WARNING: idCinematic: Cannot find an audio stream in: 'sound/vo/video/mfs.bik', 0

WARNING: idClipModel::Handle: clip model 0 on 'marscity_soldier_black_2_head' (102) is not a collision or trace model
WARNING: Couldn't load image: _emptyname : _emptyname#__0200
WARNING: idSessionLocal::Pump was not called for 3 seconds
14 warnings
 91055 msec to load game/mars_city1
--------- Game Map Shutdown ----------
--------------------------------------
********************
ERROR: Framebuffer::Check( _shadowMap3 ): Framebuffer incomplete, missing read buffer
********************
caught OpenGL error: 1286 in file D:\repos\Classic-RBDOOM-3-BFG\neo\renderer\RenderSystem.cpp line 813
--------- Game Map Shutdown ----------
--------------------------------------
********************
ERROR: Framebuffer::Check( _shadowMap3 ): Framebuffer incomplete, missing read buffer
********************

Can You Fix It

And In Case You Ask I Got The GOG Version

Specs Intel Pentium CPU B960 2.20 GHz

**Comment by MadDeCoDeR** [comment]
Try two things
A. Go to settings ->advanced settings -> and disable soft shadows
B. Copy the base/renderprogs from the source code to your game's base folder

**Comment by Robin613507** [comment]
It Better Be Fixed On The New Version

**Comment by Robin613507** [comment]
It Wont Let Me Disable The Shadow

**Comment by Robin613507** [comment]
It Works The Only Problem Is That Its Too Laggy

**Comment by MadDeCoDeR** [comment]
Doesn't your PC has a GPU ?
You might also consider to upgrade it. (Unlike OG DOOM 3 this one is more demanding.
Also try to disable the HDR

**Comment by Robin613507** [comment]
Fixed The Lag And Now It Has Another Problem It Has A Random Crash It Crashes Every 4 Hours
