### ISSUE TITLE
Some questions about Classic RBDoom 3 BFG

### ISSUE THREAD

**Issue by lmills87** [MadDeCoDeR/Classic-RBDOOM-3-BFG#45]
I am wondering, what are some of the biggest advantages of Doom: BFA over RBDoom 3 BFG?

I am trying to figure out the "best " way to experience Doom 3 again with a mostly vanilla experience but with some enhancements. My options seem limitless. There is original Doom 3 + mods (Redux for example), Dhewm + mods (Doom 3 source port) and then there's RBDoom 3 BFG and now BFA... I can't keep track of it all!

As far as I can tell, BFG seems more desirable by default since I can crank the FPS up to 120. But beyond that, why might you recommend BFA over RBDoom or vanilla BFG? And can you recommend texture packs or etc. that work with BFA?

For example, this (https://www.moddb.com/mods/doom-3-bfg-hi-def) looks pretty outstanding in that it seems to improve visuals and sounds but not gameplay, but it was last updated in 2017 and it apparently uses a custom RBDoom and not BFA? Which texture packs or graphical mods can be installed, and how is that done?

Anyways, I am very much a lay person here and just looking for some help to get the best possible enhanced Doom 3 experience, and would appreciate any and all guidance you might be able to give. It's my understanding that BFA doesn't include any enhanced textures/sounds by default; if you could point me in the right direction I would be very grateful!

Edit: Also, I noticed that it mentions "game DLL support is nearly complete" - what does this mean for me as someone who is wanting to play through the game? Does this effect me in some way or is this more for modders or something else?

**Comment by MadDeCoDeR** [comment]
BFA tries to enhance the gameplay experience of Ultimate DOOM, DOOM II and DOOM 3.
Any mod that works with RBDoom also works with BFA.

There are some addons I have made (1 of them is a port from a DOOM 3 mod and another one is just a repackage of Hi-Def that improves the loading time).
You can check them here: https://www.moddb.com/mods/classic-rbdoom-3-bfg-edition/addons

Also it has support for EAX audio by using .efx files (You can download them for DOOM 3 and DOOM 3: ROE from here: https://www.moddb.com/mods/classic-rbdoom-3-bfg-edition/downloads/roe-addon)

You can also check the Advanced Settings which allows you to adjust Player model FOV or change Flashlight mode (requires New Game).

In comparison to RBDoom and vanilla, BFA offers improved Controller support, not annoying auto saves, support for additional audio formats (ogg, mp3 and flac) and support for game dll.

Game dll even through is supported is not yet complete (remains integration with SWF UI system), this of course only affects modders and not gamers in any way.

**Comment by lmills87** [comment]
Thank you very much for the write-up; that helps a lot.

It seems to me that perhaps the best Doom 3 experience comes from a combination of Classic RbDoom 3 BFG BFA and your repackage of the Hi Def mod, or some other compatible mod or texture pack.

That leaves me with just a couple more questions -

Can I use any given texture packs? If so, how? Dragging and dropping .pk4 doesn’t seem to work. Can they only modify textures and not models? What are the conditions?

Are there any special instructions to install your repackage is the Hi Def mod?

How do I launch directly into Doom 3 and ignore the option to select Doom 1 or 2?

When installing Classic RBDoom 3 BFG BFA, can I just put the precompiled binary in a folder with only the “base” folder copied from my installed BFG Steam directory, and that’s all I need (just the BFA exe and “base”)?

Or alternatively, can I drag and drop the BFA exe into my installed Steam BFG folder and re-name it so it gets launched instead of the normal Doom3BFG exe when launching from Steam? Or is it imperative to create a fresh directory for BFA as described above?

Thanks again for the help. I’ve been combing through documentation trying to find answers to these questions and so far haven’t had much luck, but you have clarified a lot for me.

**Comment by MadDeCoDeR** [comment]
If it is targeted for BFG then absolutely, if not just give a try and see if it works.

Like OG DOOM 3 the mods must be inside folders, unlike OG DOOM 3 it does not support pk4 files but there is the pk4toBFG which is a simple file extractor that extract one or more .pk4 files into a single folder that can be loaded as a mod.

Except of the Main menu UI, HUD and PDAs (which are using SWF UI System) you can modify EVERYTHING.

Just drop the Hi-Def folder into the game's directory (either vanilla or BFA) and ten either use the BFA Launcher (CDL.exe) to set it either as a mod or mod base (if you want the textures with custom map mods) or use the launch arguments _+set fs_game_ or _+set fs_game_base_. 
NOTE: I haven't test it on vanilla but since it is packaged in .resources it might load.

Either with the Launcher (CDL.exe) by setting _Select game to launch_ to DOOM 3 or with the launch argument _+set com_game_mode 3_.

Yes, but also the BFA files are not conflicting with the vanilla files (except the 32bit version which replace the steam_api.dll)

**Comment by lmills87** [comment]
In terms of your own opinion - what do you think is the best way to experience Doom 3? BFA + Hi Def? Anything else I might want to consider if I’m looking for a mostly vanilla experience?

**Comment by MadDeCoDeR** [comment]
I usually play with BFA + Hi Def and with the original flashlight mode. 
Regarding G-Sync (or Free-sync Which I use) I let V-sync on Smart (limit FPS as long as it can be limited) and it plays quite smooth (@75FPS which is the max refresh rate on my monitor).

**Comment by lmills87** [comment]
Fired up BFA tonight. I haven't tried your Hi Def repackage just yet. But I've run into a couple issues.

The most glaring of which is that the lights seem to flicker quite a bit when moving. I can upload a video if you'd like to see this in action. Disabling HDR seems to fix the issue.

What does the view model FOV do? I can apparently only increase this value in the options menu, and once the slider is full, I can't seem to decrease it. How can I decrease this value or perhaps access the parameter itself and change it back to (presumably) zero? Where are those parameters stored?

What is SSGI?

Aside from the flickering issue, I'm really liking the quality of life improvements that I'm seeing in BFA so far.

**Comment by MadDeCoDeR** [comment]
It put the players hands further away from his view. Use the left and right arrows to adjust the value in the menu.

Is Screen Sample Global Illumination. It comes bundled (like HDR and Soft Shadows) from RBDoom (from which this port is based on)

**Comment by lmills87** [comment]
Hmm; I think I tried the arrow keys and it didn't work. Or perhaps I tried A/D and not the arrow keys... I'll have to check.

Here is the flickering that I'm experiencing:

https://www.youtube.com/watch?v=9fusbBvx2rg

Any ideas?

**Comment by MadDeCoDeR** [comment]
I thought this was part from them Map. 
Sorry but no idea, you might want to check it with RBDoom too and if the same happens then report it to them (they might be able to fix it).

**Comment by lmills87** [comment]
Disabling HDR autoexposure seems to fix the problem (while being able to leave HDR enabled). I started an issue over on RBDoom3. Do you know if it's possible to make the HDR a bit less bright?

Also, is there a list of all relevant cvars and their descriptions somewhere?

**Comment by xcom169** [comment]
Do you use D3 Redux or [DooM 3 Essential HD Pack v2.0 - 2025 update] mods to improve the graphics?
