### ISSUE TITLE
Short bug report: Mouse wheel + 1080p

### ISSUE THREAD

**Issue by XploitOcelot** [MadDeCoDeR/Classic-RBDOOM-3-BFG#46]
Hi. Thanks on the first place for working on this amazing project.
I have a couple of problems with Doom BFA. The first, I cannot set fullscreen resolution on 1920x1080 because the image gets cut and only a portion is seen on the whole screen. I just use 1280x720 while I wait for it to (maybe) get resolved.
Second, is that if I use the mouse wheel at the start menu in Doom 1, the game instantly crashes.

Sorry if I'm not clear. My technical english is not that rich.

**Comment by MadDeCoDeR** [comment]
For the first what is you desktop resolution ? I am aware that If you set the game resolution higher than your desktop resolution it might have these issue.

For the second I just pushed some source code changes I have done and one of them is resolving that issue. You must download the source code and compile it on your own (right now I am not making new pre-built binaries sorry)

**Comment by XploitOcelot** [comment]
> 
> 
> For the first what is you desktop resolution ? I am aware that If you set the game resolution higher than your desktop resolution it might have these issue.
> 
> For the second I just pushed some source code changes I have done and one of them is resolving that issue. You must download the source code and compile it on your own (right now I am not making new pre-built binaries sorry)

Hi! Thanks for answering!
My desktop resolution is 1920x1080. that's why I don't understand getting a cut image...

Talking about the second one, I don't mind waiting for trying the next build. If you are already aware that's more than enough, from my pow.

**Comment by MadDeCoDeR** [comment]
That's odd I also run it with the same resolution and I don't have this issue what specs do you have? Have you set up anything on your GPU control panel ?

**Comment by XploitOcelot** [comment]
> 
> 
> That's odd I also run it with the same resolution and I don't have this issue what specs do you have? Have you set up anything on your GPU control panel ?
If I select 1920x1080 it cuts the image in fullscreen everytime I restart the game.
I will just stick to 1600x900. Everything fine with that resolution.
And no, nothing special set. Windows 10, GeForce GTX 950M, 8GB RAM... I don't know

**Comment by MadDeCoDeR** [comment]
For the resolution did you happen to have DSR enabled on your GPU ?

**Comment by MadDeCoDeR** [comment]
The new version is now out and probaply is also including a fix for the resolution (hopping the problem was with the DPI)

**Comment by MadDeCoDeR** [comment]
No report for the issue keep existing . Closing
