### ISSUE TITLE
Flashlight in Lost Mission doesn't work

### ISSUE THREAD

**Issue by ElTioRata** [MadDeCoDeR/Classic-RBDOOM-3-BFG#47]
For some reason when I start Lost Mission with the original flashlight, it doesn't appear, I press F and nothing happens.

**Comment by MadDeCoDeR** [comment]
That is known issue and it will be fixed on the next release.
The flashlight will be available on the second level and onwards.

**Comment by MadDeCoDeR** [comment]
And the new version is now out and includes the original flashlight for the first mission of Lost Mission
