### ISSUE TITLE
More bug reports

### ISSUE THREAD

**Issue by ElTioRata** [MadDeCoDeR/Classic-RBDOOM-3-BFG#48]
- Original flashlight has no description or image at all in the PDA:
![20200402160044_1](https://user-images.githubusercontent.com/19964653/78294150-381b8980-7500-11ea-922c-2b7118e92b54.jpg)
- Weapons with "ammo viewfinder" have issues with the lighting:
![20200402160708_1](https://user-images.githubusercontent.com/19964653/78294158-3ce03d80-7500-11ea-97e7-d953ff089ef0.jpg)
![20200402162035_1](https://user-images.githubusercontent.com/19964653/78294168-410c5b00-7500-11ea-864c-9b99e796ae8a.jpg)
- Big red circle when grabbing something with the Grabber:
![20200402160914_1](https://user-images.githubusercontent.com/19964653/78294175-44074b80-7500-11ea-8e93-2707898b2ac1.jpg)
- Original flashlight lighting fades away when getting close to a certain surface:
![20200402162357_1](https://user-images.githubusercontent.com/19964653/78294179-479ad280-7500-11ea-968a-2f4a32d72039.jpg)
- Missing spanish (and probably other languages) translation for Auto Save bar:
![20200402162404_1](https://user-images.githubusercontent.com/19964653/78294184-49fd2c80-7500-11ea-80ec-5bc3b43899b6.jpg)

**Comment by ElTioRata** [comment]
As far as I know, the flashlight fade bug can be executed in anywhere. Just get closer to any wall.

**Comment by MadDeCoDeR** [comment]
Well, I didn't manage to fix the graphical issues but I made all the new ui strings translatable and added (with the help of google translate) translation for all the languages

**Comment by MadDeCoDeR** [comment]
All there issues seems to be fixed by now. Close
