### ISSUE TITLE
Problem with Windows desktop scaling

### ISSUE THREAD

**Issue by TheVoodoo** [MadDeCoDeR/Classic-RBDOOM-3-BFG#49]
If windows desktop scaling is activated above 100%, BFA wont display the whole screenarea if the game resolution is set higher than 720p.

In my case, im running the desktop at 125% scale and the game at native resolution 2560x1440...
This doesn't happen with the original Doom3BFG executable when using the same settings, so it has to be a RBDoom/BFA related problem.

OS: Win10 v1909

![grafik](https://user-images.githubusercontent.com/16653359/78454787-8a90ad80-769a-11ea-976c-67dc8d7d52e0.png)

![grafik](https://user-images.githubusercontent.com/16653359/78454893-376b2a80-769b-11ea-8430-65a0b22500c1.png)

**Comment by MadDeCoDeR** [comment]
It quite known issue. It might be due to the new fullscreen code I have put in (more safe than before). I will investigate further and hopefully a fix for that issue will come in future releases (probably not the next one)

**Comment by MadDeCoDeR** [comment]
Well as it turn out the only thing I had to do was to make it DPI aware.
The new version is now available and the fix is included.

**Comment by TheVoodoo** [comment]
Weird... above 720p it works now as intended (thx for that) but it introduced a new bug...
When switching to 1280x720 it won't fill the screen at all ;)
I also noticed that the "revert" button doesn't work anymore.

**Comment by MadDeCoDeR** [comment]
For the resolution, quick question dio you happen to have something like integer scaling active in your GPU ? I just test on mine (AMD RX 570) and once I disabled that the game was properly scaling to 720p.
As for the second welp that is something I forgot to change with the new fullscreen algorithm thanks for mentioning it.

**Comment by MadDeCoDeR** [comment]
And just reupload it with the fix for the revert button

**Comment by TheVoodoo** [comment]
I'm using a nvidia GTX1070. I'm not familiar with the integer scaling feature, but i checked the GPU settings and it seems that any setting that include scaling is disabled. I made a short video, it might help...

https://youtu.be/DAGEKMIUAuo

Btw, at video timestamp 0:53 i noticed another bug... If you click once in options on the arrow left/right selection, it infinitely circles through that option. You have to move the cursor away to make it stop.

**Comment by MadDeCoDeR** [comment]
I checked it with another PC that had nVidia and it seems that most likley to occur if you have toyed around with the _adjust desktop size and position_ settings, try to set it on fullscreen and check how it behaves with both the GPU and the display scaling, and al;so see what the checkbox behaviour is.

**Comment by MadDeCoDeR** [comment]
New nightly releases come with a newer Windows 10 DPI awareness API. You can check if it resolves the issue

**Comment by MadDeCoDeR** [comment]
It has been an year without a response. Closing issue
