### ISSUE TITLE
GPL violation?

### ISSUE THREAD

**Issue by mastan-rus** [MadDeCoDeR/Classic-RBDOOM-3-BFG#50]
Binary releases include Open Platform(MIT license) and steam_api(some closed license) dlls.

But according to GPL, closed-source libraries cannot be distributed together: https://www.gnu.org/licenses/gpl-faq.html#WindowsRuntimeAndGPL

> I'm writing a Windows application with Microsoft Visual C++ (or Visual Basic) and I will be releasing it under the GPL. Is dynamically linking my program with the Visual C++ (or Visual Basic) runtime library permitted under the GPL?

> You may not distribute these libraries in compiled DLL form with the program. To prevent unscrupulous distributors from trying to use the System Library exception as a loophole, the GPL says that libraries can only qualify as System Libraries as long as they're not distributed with the program itself. If you distribute the DLLs with the program, they won't be eligible for this exception anymore; then the only way to comply with the GPL would be to provide their source code, which you are unable to do.

Well, Open Platform is probably fine due to its source being provided even though it's not GPL, but I think including steam_api.dll violates this.

**Comment by MadDeCoDeR** [comment]
Well, in that occasion I will stop distributing them. Thanks for mentioning it.

**Comment by MadDeCoDeR** [comment]
And just reuploaded all version since 1.1.12.11 and removed the steam dll.
From now on if anyone wants steam achievements will have to download separately the Open platform with steam (closed source but free) and manually install it.
Thanks for bringing it up.
