### ISSUE TITLE
Updated, now my game looks like this (language packs broken)

### ISSUE THREAD

**Issue by ElTioRata** [MadDeCoDeR/Classic-RBDOOM-3-BFG#51]
![Sin título](https://user-images.githubusercontent.com/19964653/79079567-58a8c800-7ce6-11ea-93b6-f4c3abdaa98e.png)

**Comment by MadDeCoDeR** [comment]
For now try to launch it with +set sys_lang "spanish"

**Comment by ElTioRata** [comment]
Now it works. I added some adjustments to the Spanish translation.

**Comment by MadDeCoDeR** [comment]
Thanks, I already merged it and I am closing this issue.
