### ISSUE TITLE
Next Weapon and Previous Weapon binds are incorrect in Doom 3

### ISSUE THREAD

**Issue by guynamederick** [MadDeCoDeR/Classic-RBDOOM-3-BFG#53]
I have just set up version 1.2.5 and after setting my key binds, I noticed something odd when playing between Doom 1/2 and Doom 3. For Doom 3, the bind "Next Weapon" is actually "Previous Weapon" and the bind "Previous Weapon" is actually "Next Weapon" for some odd reason.  Since Doom 1/2 in BFA share these two binds, going into the control settings displays the binds correctly, basically meaning that "Next Weapon" and "Previous Weapon" are what they actually are.

I tested this by loading into Doom 3 and using "give all" and going into Doom 1 and using "idkfa". In Doom 1, going from the fists to the BFG works fine when using the "Next Weapon" bind. In Doom 3, using "Next Weapon" doesn't take me from my fists to the BFG, instead I have the Soul Cube on me instead.

This strange issue is not present in the original BFG Edition.

**Comment by MadDeCoDeR** [comment]
The issue is resolved quite some time now. This issue will now close.
