### ISSUE TITLE
Unable to initialise OpenGL

### ISSUE THREAD

**Issue by SpeedStriker243** [MadDeCoDeR/Classic-RBDOOM-3-BFG#55]
I've tried using the standard ZIP file and Windows installer for Doom BFA and the same error dialog always pops up.
```
QA Timing INIT: 000000ms
DOOM BFA 1.2.6.1403 win-x86 Jul 28 2020 23:30:13
2304 MHz Intel CPU with MMX & SSE & SSE2 & SSE3 & HTT
Winsock Initialized
Found interface: {E552D6B6-234B-4169-B14C-128264E83F40} Realtek PCIe GBE Family Controller - 0.0.0.0 NULL netmask - skipped
Found interface: {69B98C91-D42E-4C5C-8C7D-10C7417469E4} Bluetooth Device (Personal Area Network) - 0.0.0.0 NULL netmask - skipped
Found interface: {AEF2CEFD-695D-4B8E-921E-4068EB5A6BC4} VMware Virtual Ethernet Adapter for VMnet1 - 192.168.203.1/255.255.255.0
Found interface: {E84C9109-B85C-4578-9E06-2E6468F5C75A} VMware Virtual Ethernet Adapter for VMnet8 - 192.168.231.1/255.255.255.0
Found interface: {4B9D265B-1D5A-4908-AB51-7DCB8181FAA9} VirtualBox Host-Only Ethernet Adapter - 192.168.56.1/255.255.255.0
Found interface: {8A447BEB-C459-424A-88B6-25D8C97E5C45} Intel(R) Dual Band Wireless-AC 7265 - 192.168.1.61/255.255.255.0
Found interface: {B3569FAC-00B0-49EC-AA9E-CF32A4C57C77} Microsoft Wi-Fi Direct Virtual Adapter - 0.0.0.0 NULL netmask - skipped
Found interface: {E8AC0DC1-8FD4-45A8-A823-7225B0561DB4} Microsoft Wi-Fi Direct Virtual Adapter #2 - 0.0.0.0 NULL netmask - skipped
Sys_InitNetworking: adding loopback interface
doom using MMX & SSE for SIMD processing
enabled Flush-To-Zero mode
enabled Denormals-Are-Zero mode
------ Initializing File System ------
Loaded resource file _common.resources
Loaded resource file _ordered.resources
Loaded resource file _sound_pc.resources
Loaded resource file _sound_pc_en.resources
Loaded resource file maps/admin.resources
Loaded resource file maps/alphalabs1.resources
Loaded resource file maps/alphalabs2.resources
Loaded resource file maps/alphalabs3.resources
Loaded resource file maps/alphalabs4.resources
Loaded resource file maps/caverns1.resources
Loaded resource file maps/caverns2.resources
Loaded resource file maps/comm1.resources
Loaded resource file maps/commoutside.resources
Loaded resource file maps/cpu.resources
Loaded resource file maps/cpuboss.resources
Loaded resource file maps/d3ctf1.resources
Loaded resource file maps/d3ctf2.resources
Loaded resource file maps/d3ctf3.resources
Loaded resource file maps/d3ctf4.resources
Loaded resource file maps/d3dm1.resources
Loaded resource file maps/d3dm2.resources
Loaded resource file maps/d3dm3.resources
Loaded resource file maps/d3dm4.resources
Loaded resource file maps/d3dm5.resources
Loaded resource file maps/d3xpdm1.resources
Loaded resource file maps/d3xpdm2.resources
Loaded resource file maps/d3xpdm3.resources
Loaded resource file maps/d3xpdm4.resources
Loaded resource file maps/delta1.resources
Loaded resource file maps/delta2a.resources
Loaded resource file maps/delta2b.resources
Loaded resource file maps/delta3.resources
Loaded resource file maps/delta4.resources
Loaded resource file maps/delta5.resources
Loaded resource file maps/deltax.resources
Loaded resource file maps/enpro.resources
Loaded resource file maps/erebus1.resources
Loaded resource file maps/erebus2.resources
Loaded resource file maps/erebus3.resources
Loaded resource file maps/erebus4.resources
Loaded resource file maps/erebus5.resources
Loaded resource file maps/erebus6.resources
Loaded resource file maps/hell.resources
Loaded resource file maps/hell1.resources
Loaded resource file maps/hellhole.resources
Loaded resource file maps/le_enpro1.resources
Loaded resource file maps/le_enpro2.resources
Loaded resource file maps/le_exis1.resources
Loaded resource file maps/le_exis2.resources
Loaded resource file maps/le_hell.resources
Loaded resource file maps/le_hell_post.resources
Loaded resource file maps/le_underground.resources
Loaded resource file maps/le_underground2.resources
Loaded resource file maps/mars_city1.resources
Loaded resource file maps/mars_city2.resources
Loaded resource file maps/mc_underground.resources
Loaded resource file maps/monorail.resources
Loaded resource file maps/phobos1.resources
Loaded resource file maps/phobos2.resources
Loaded resource file maps/phobos3.resources
Loaded resource file maps/phobos4.resources
Loaded resource file maps/recycling1.resources
Loaded resource file maps/recycling2.resources
Loaded resource file maps/site3.resources
Loaded resource file maps/zBFA.resources
Loaded resource file maps/zfixed_le_model.resources
Current search path:
C:\Users\sonic\Saved Games\id Software\DOOM BFA/base
X:\SteamLibrary\steamapps\common\DOOM 3 BFG Edition/base
_common.resources
_ordered.resources
_sound_pc.resources
_sound_pc_en.resources
maps/admin.resources
maps/alphalabs1.resources
maps/alphalabs2.resources
maps/alphalabs3.resources
maps/alphalabs4.resources
maps/caverns1.resources
maps/caverns2.resources
maps/comm1.resources
maps/commoutside.resources
maps/cpu.resources
maps/cpuboss.resources
maps/d3ctf1.resources
maps/d3ctf2.resources
maps/d3ctf3.resources
maps/d3ctf4.resources
maps/d3dm1.resources
maps/d3dm2.resources
maps/d3dm3.resources
maps/d3dm4.resources
maps/d3dm5.resources
maps/d3xpdm1.resources
maps/d3xpdm2.resources
maps/d3xpdm3.resources
maps/d3xpdm4.resources
maps/delta1.resources
maps/delta2a.resources
maps/delta2b.resources
maps/delta3.resources
maps/delta4.resources
maps/delta5.resources
maps/deltax.resources
maps/enpro.resources
maps/erebus1.resources
maps/erebus2.resources
maps/erebus3.resources
maps/erebus4.resources
maps/erebus5.resources
maps/erebus6.resources
maps/hell.resources
maps/hell1.resources
maps/hellhole.resources
maps/le_enpro1.resources
maps/le_enpro2.resources
maps/le_exis1.resources
maps/le_exis2.resources
maps/le_hell.resources
maps/le_hell_post.resources
maps/le_underground.resources
maps/le_underground2.resources
maps/mars_city1.resources
maps/mars_city2.resources
maps/mc_underground.resources
maps/monorail.resources
maps/phobos1.resources
maps/phobos2.resources
maps/phobos3.resources
maps/phobos4.resources
maps/recycling1.resources
maps/recycling2.resources
maps/site3.resources
maps/zBFA.resources
maps/zfixed_le_model.resources
file system initialized.
--------------------------------------
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
execing default.cfg
execing joy_360_0.cfg
execing joy_righty.cfg
couldn't exec DBFAConfig.cfg
couldn't exec autoexec.cfg
Initializing Platform
----- R_InitOpenGL -----
Initializing OpenGL subsystem with multisamples:0 stereo:0 fullscreen:1
...registered window class
...registered fake window class
Using GLEW 2.1.0
display device: 0
  DeviceName  : \\.\DISPLAY1
  DeviceString: Intel(R) HD Graphics 530
  StateFlags  : 0x8000005
  DeviceID    : PCI\VEN_8086&DEV_191B&SUBSYS_1C5D1043&REV_06
  DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Video\{001E9AC1-816B-11E9-847D-005056C00001}\0000
      DeviceName  : \\.\DISPLAY1\Monitor0
      DeviceString: Generic PnP Monitor
      StateFlags  : 0x2
      DeviceID    : MONITOR\AUO38ED\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
      DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
          dmPosition.x      : 0
          dmPosition.y      : 0
          dmBitsPerPel      : 32
          dmPelsWidth       : 1920
          dmPelsHeight      : 1080
          dmDisplayFlags    : 0x0
          dmDisplayFrequency: 60
display device: 0
  DeviceName  : \\.\DISPLAY1
  DeviceString: Intel(R) HD Graphics 530
  StateFlags  : 0x8000005
  DeviceID    : PCI\VEN_8086&DEV_191B&SUBSYS_1C5D1043&REV_06
  DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Video\{001E9AC1-816B-11E9-847D-005056C00001}\0000
      DeviceName  : \\.\DISPLAY1\Monitor0
      DeviceString: Generic PnP Monitor
      StateFlags  : 0x2
      DeviceID    : MONITOR\AUO38ED\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
      DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
          dmPosition.x      : 0
          dmPosition.y      : 0
          dmBitsPerPel      : 32
          dmPelsWidth       : 1920
          dmPelsHeight      : 1080
          dmDisplayFlags    : 0x0
          dmDisplayFrequency: 60
...created window @ 0,0 (1920x1080)
Initializing OpenGL driver
...creating GL context: failed to create OpenGL 4.5 context
failed to create OpenGL 4.5 context
unknown error: 0x5
failed
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed
...releasing DC: failed
Initializing OpenGL subsystem with multisamples:0 stereo:0 fullscreen:1
Using GLEW 2.1.0
display device: 0
  DeviceName  : \\.\DISPLAY1
  DeviceString: Intel(R) HD Graphics 530
  StateFlags  : 0x8000005
  DeviceID    : PCI\VEN_8086&DEV_191B&SUBSYS_1C5D1043&REV_06
  DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Video\{001E9AC1-816B-11E9-847D-005056C00001}\0000
      DeviceName  : \\.\DISPLAY1\Monitor0
      DeviceString: Generic PnP Monitor
      StateFlags  : 0x2
      DeviceID    : MONITOR\AUO38ED\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
      DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
          dmPosition.x      : 0
          dmPosition.y      : 0
          dmBitsPerPel      : 32
          dmPelsWidth       : 1920
          dmPelsHeight      : 1080
          dmDisplayFlags    : 0x0
          dmDisplayFrequency: 60
...calling CDS: ok
display device: 0
  DeviceName  : \\.\DISPLAY1
  DeviceString: Intel(R) HD Graphics 530
  StateFlags  : 0x8000005
  DeviceID    : PCI\VEN_8086&DEV_191B&SUBSYS_1C5D1043&REV_06
  DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Video\{001E9AC1-816B-11E9-847D-005056C00001}\0000
      DeviceName  : \\.\DISPLAY1\Monitor0
      DeviceString: Generic PnP Monitor
      StateFlags  : 0x2
      DeviceID    : MONITOR\AUO38ED\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
      DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
          dmPosition.x      : 0
          dmPosition.y      : 0
          dmBitsPerPel      : 32
          dmPelsWidth       : 1280
          dmPelsHeight      : 720
          dmDisplayFlags    : 0x0
          dmDisplayFrequency: 60
...created window @ 0,0 (1280x720)
Initializing OpenGL driver
...creating GL context: failed to create OpenGL 4.5 context
failed to create OpenGL 4.5 context
unknown error: 0x5
failed
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed
...releasing DC: failed
...resetting display
Initializing OpenGL subsystem with multisamples:0 stereo:0 fullscreen:0
Using GLEW 2.1.0
...created window @ 0,0 (1296x759)
Initializing OpenGL driver
...creating GL context: failed to create OpenGL 4.5 context
failed to create OpenGL 4.5 context
unknown error: 0x5
failed
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed
...releasing DC: failed
Unable to initialize OpenGL
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed
```

**Comment by SpeedStriker243** [comment]
Never mind, turns out I just need to update my OpenGL version.

**Comment by SpeedStriker243** [comment]
Okay, so apparently I have **OpenGL 4.6** according to Steam, but it doesn't make a difference.

**Comment by MadDeCoDeR** [comment]
Have you try to open it with the launch argument +set r_useOpenGLProfile 0 ?

**Comment by SpeedStriker243** [comment]
Tried that, now it complains with this:
``
QA Timing INIT: 000000ms
DOOM BFA 1.2.6.1403 win-x86 Jul 28 2020 23:30:13
2304 MHz Intel CPU with MMX & SSE & SSE2 & SSE3 & HTT
Winsock Initialized
Found interface: {E552D6B6-234B-4169-B14C-128264E83F40} Realtek PCIe GBE Family Controller - 0.0.0.0 NULL netmask - skipped
Found interface: {69B98C91-D42E-4C5C-8C7D-10C7417469E4} Bluetooth Device (Personal Area Network) - 0.0.0.0 NULL netmask - skipped
Found interface: {AEF2CEFD-695D-4B8E-921E-4068EB5A6BC4} VMware Virtual Ethernet Adapter for VMnet1 - 192.168.203.1/255.255.255.0
Found interface: {E84C9109-B85C-4578-9E06-2E6468F5C75A} VMware Virtual Ethernet Adapter for VMnet8 - 192.168.231.1/255.255.255.0
Found interface: {4B9D265B-1D5A-4908-AB51-7DCB8181FAA9} VirtualBox Host-Only Ethernet Adapter - 192.168.56.1/255.255.255.0
Found interface: {8A447BEB-C459-424A-88B6-25D8C97E5C45} Intel(R) Dual Band Wireless-AC 7265 - 192.168.1.61/255.255.255.0
Found interface: {B3569FAC-00B0-49EC-AA9E-CF32A4C57C77} Microsoft Wi-Fi Direct Virtual Adapter - 0.0.0.0 NULL netmask - skipped
Found interface: {E8AC0DC1-8FD4-45A8-A823-7225B0561DB4} Microsoft Wi-Fi Direct Virtual Adapter #2 - 0.0.0.0 NULL netmask - skipped
Sys_InitNetworking: adding loopback interface
doom using MMX & SSE for SIMD processing
enabled Flush-To-Zero mode
enabled Denormals-Are-Zero mode
------ Initializing File System ------
Loaded resource file _common.resources
Loaded resource file _ordered.resources
Loaded resource file _sound_pc.resources
Loaded resource file _sound_pc_en.resources
Loaded resource file maps/admin.resources
Loaded resource file maps/alphalabs1.resources
Loaded resource file maps/alphalabs2.resources
Loaded resource file maps/alphalabs3.resources
Loaded resource file maps/alphalabs4.resources
Loaded resource file maps/caverns1.resources
Loaded resource file maps/caverns2.resources
Loaded resource file maps/comm1.resources
Loaded resource file maps/commoutside.resources
Loaded resource file maps/cpu.resources
Loaded resource file maps/cpuboss.resources
Loaded resource file maps/d3ctf1.resources
Loaded resource file maps/d3ctf2.resources
Loaded resource file maps/d3ctf3.resources
Loaded resource file maps/d3ctf4.resources
Loaded resource file maps/d3dm1.resources
Loaded resource file maps/d3dm2.resources
Loaded resource file maps/d3dm3.resources
Loaded resource file maps/d3dm4.resources
Loaded resource file maps/d3dm5.resources
Loaded resource file maps/d3xpdm1.resources
Loaded resource file maps/d3xpdm2.resources
Loaded resource file maps/d3xpdm3.resources
Loaded resource file maps/d3xpdm4.resources
Loaded resource file maps/delta1.resources
Loaded resource file maps/delta2a.resources
Loaded resource file maps/delta2b.resources
Loaded resource file maps/delta3.resources
Loaded resource file maps/delta4.resources
Loaded resource file maps/delta5.resources
Loaded resource file maps/deltax.resources
Loaded resource file maps/enpro.resources
Loaded resource file maps/erebus1.resources
Loaded resource file maps/erebus2.resources
Loaded resource file maps/erebus3.resources
Loaded resource file maps/erebus4.resources
Loaded resource file maps/erebus5.resources
Loaded resource file maps/erebus6.resources
Loaded resource file maps/hell.resources
Loaded resource file maps/hell1.resources
Loaded resource file maps/hellhole.resources
Loaded resource file maps/le_enpro1.resources
Loaded resource file maps/le_enpro2.resources
Loaded resource file maps/le_exis1.resources
Loaded resource file maps/le_exis2.resources
Loaded resource file maps/le_hell.resources
Loaded resource file maps/le_hell_post.resources
Loaded resource file maps/le_underground.resources
Loaded resource file maps/le_underground2.resources
Loaded resource file maps/mars_city1.resources
Loaded resource file maps/mars_city2.resources
Loaded resource file maps/mc_underground.resources
Loaded resource file maps/monorail.resources
Loaded resource file maps/phobos1.resources
Loaded resource file maps/phobos2.resources
Loaded resource file maps/phobos3.resources
Loaded resource file maps/phobos4.resources
Loaded resource file maps/recycling1.resources
Loaded resource file maps/recycling2.resources
Loaded resource file maps/site3.resources
Loaded resource file maps/zBFA.resources
Loaded resource file maps/zfixed_le_model.resources
Current search path:
C:\Users\sonic\Saved Games\id Software\DOOM BFA/base
X:\SteamLibrary\steamapps\common\DOOM 3 BFG Edition/base
_common.resources
_ordered.resources
_sound_pc.resources
_sound_pc_en.resources
maps/admin.resources
maps/alphalabs1.resources
maps/alphalabs2.resources
maps/alphalabs3.resources
maps/alphalabs4.resources
maps/caverns1.resources
maps/caverns2.resources
maps/comm1.resources
maps/commoutside.resources
maps/cpu.resources
maps/cpuboss.resources
maps/d3ctf1.resources
maps/d3ctf2.resources
maps/d3ctf3.resources
maps/d3ctf4.resources
maps/d3dm1.resources
maps/d3dm2.resources
maps/d3dm3.resources
maps/d3dm4.resources
maps/d3dm5.resources
maps/d3xpdm1.resources
maps/d3xpdm2.resources
maps/d3xpdm3.resources
maps/d3xpdm4.resources
maps/delta1.resources
maps/delta2a.resources
maps/delta2b.resources
maps/delta3.resources
maps/delta4.resources
maps/delta5.resources
maps/deltax.resources
maps/enpro.resources
maps/erebus1.resources
maps/erebus2.resources
maps/erebus3.resources
maps/erebus4.resources
maps/erebus5.resources
maps/erebus6.resources
maps/hell.resources
maps/hell1.resources
maps/hellhole.resources
maps/le_enpro1.resources
maps/le_enpro2.resources
maps/le_exis1.resources
maps/le_exis2.resources
maps/le_hell.resources
maps/le_hell_post.resources
maps/le_underground.resources
maps/le_underground2.resources
maps/mars_city1.resources
maps/mars_city2.resources
maps/mc_underground.resources
maps/monorail.resources
maps/phobos1.resources
maps/phobos2.resources
maps/phobos3.resources
maps/phobos4.resources
maps/recycling1.resources
maps/recycling2.resources
maps/site3.resources
maps/zBFA.resources
maps/zfixed_le_model.resources
file system initialized.
--------------------------------------
WARNING: Unable to open resource file maps/_startup.resources
----- Initializing Decls -----
------------------------------
Couldn't open journal files
execing default.cfg
execing joy_360_0.cfg
execing joy_righty.cfg
couldn't exec DBFAConfig.cfg
couldn't exec autoexec.cfg
Initializing Platform
----- R_InitOpenGL -----
Initializing OpenGL subsystem with multisamples:0 stereo:0 fullscreen:1
...registered window class
...registered fake window class
Using GLEW 2.1.0
display device: 0
  DeviceName  : \\.\DISPLAY1
  DeviceString: Intel(R) HD Graphics 530
  StateFlags  : 0x8000005
  DeviceID    : PCI\VEN_8086&DEV_191B&SUBSYS_1C5D1043&REV_06
  DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Video\{001E9AC1-816B-11E9-847D-005056C00001}\0000
      DeviceName  : \\.\DISPLAY1\Monitor0
      DeviceString: Generic PnP Monitor
      StateFlags  : 0x2
      DeviceID    : MONITOR\AUO38ED\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
      DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
          dmPosition.x      : 0
          dmPosition.y      : 0
          dmBitsPerPel      : 32
          dmPelsWidth       : 1920
          dmPelsHeight      : 1080
          dmDisplayFlags    : 0x0
          dmDisplayFrequency: 60
display device: 0
  DeviceName  : \\.\DISPLAY1
  DeviceString: Intel(R) HD Graphics 530
  StateFlags  : 0x8000005
  DeviceID    : PCI\VEN_8086&DEV_191B&SUBSYS_1C5D1043&REV_06
  DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Video\{001E9AC1-816B-11E9-847D-005056C00001}\0000
      DeviceName  : \\.\DISPLAY1\Monitor0
      DeviceString: Generic PnP Monitor
      StateFlags  : 0x2
      DeviceID    : MONITOR\AUO38ED\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
      DeviceKey   : \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0002
          dmPosition.x      : 0
          dmPosition.y      : 0
          dmBitsPerPel      : 32
          dmPelsWidth       : 1920
          dmPelsHeight      : 1080
          dmDisplayFlags    : 0x0
          dmDisplayFrequency: 60
...created window @ 0,0 (1920x1080)
Initializing OpenGL driver
...creating GL context: succeeded
...making context current: succeeded
Using GLEW 2.1.0

------- Input Initialization -------
Initializing DirectInput...
mouse: DirectInput initialized.
keyboard: DirectInput initialized.
------------------------------------
OpenGL Version   : 4.4
OpenGL Vendor    : Intel
OpenGL Renderer  : Intel(R) HD Graphics 530
OpenGL GLSL      : 4.4
idCommon::VPrintf: truncated to 4094 characters
OpenGL Extensions: GL_3DFX_texture_compression_FXT1 GL_AMD_depth_clamp_separate GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_cl_event GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_fragment_shader_interlock GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_occlusion_query2 GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_post_depth_coverage GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_robustness_isolation GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counters GL_ARB_shader_bit_encoding GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_stencil_export GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shading_language_100 GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_shadow GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_border_clamp GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_cube_map_array GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_mirrored_repeat GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transpose_matrix GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ARB_window_pos GL_ATI_separate_stencil GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_EXT_direct_state_access GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader   maxTextureAnisotropy: 16.000000
...using GL_EXT_texture_lod_bias
X..GL_GREMEDY_string_marker not found
...using GL_ARB_framebuffer_object
...using GL_EXT_framebuffer_blit
----- Initializing Render Shaders -----
While compiling vertex program renderprogs/gui.vs.hlsl
-----------------
  1: // filename renderprogs/gui.vs.hlsl
  2: #version 450
  3: #pragma shader_stage( vertex )
  4: #extension GL_ARB_separate_shader_objects : enable
  5: 
  6: 
  7: uniform vec4 _va_[4];
  8: 
  9: float dot4 (vec4 a , vec4 b ) {return dot ( a , b ) ; }
 10: float dot4 (vec2 a , vec4 b ) {return dot ( vec4 ( a , 0 , 1 ) , b ) ; }
 11: vec4 swizzleColor (vec4 c ) {
 12: 	return c ;
 13: }
 14: 
 15: in vec4 in_Position;
 16: in vec2 in_TexCoord;
 17: in vec4 in_Normal;
 18: in vec4 in_Tangent;
 19: in vec4 in_Color;
 20: in vec4 in_Color2;
 21: 
 22: out vec2 vofi_TexCoord0;
 23: out vec4 vofi_TexCoord1;
 24: out vec4 vofi_Color;
 25: 
 26: void main() {
 27: 	gl_Position . x = dot4 ( in_Position , _va_[0 /* rpMVPmatrixX */] ) ;
 28: 	gl_Position . y = dot4 ( in_Position , _va_[1 /* rpMVPmatrixY */] ) ;
 29: 	gl_Position . z = dot4 ( in_Position , _va_[2 /* rpMVPmatrixZ */] ) ;
 30: 	gl_Position . w = dot4 ( in_Position , _va_[3 /* rpMVPmatrixW */] ) ;
 31: 	vofi_TexCoord0 . xy = in_TexCoord . xy ;
 32: 	vofi_TexCoord1 = ( ( in_Color2 ) * 2.0 ) - 1.0 ;
 33: 	vofi_Color = swizzleColor ( in_Color ) ;
 34: }
-----------------
ERROR: 0:2: '' :  incorrect GLSL version: 450


While compiling fragment program renderprogs/gui.ps.hlsl
-----------------
  1: // filename renderprogs/gui.ps.hlsl
  2: #version 450
  3: #pragma shader_stage( fragment )
  4: #extension GL_ARB_separate_shader_objects : enable
  5: 
  6: void clip( float v ) { if ( v < 0.0 ) { discard; } }
  7: void clip( vec2 v ) { if ( any( lessThan( v, vec2( 0.0 ) ) ) ) { discard; } }
  8: void clip( vec3 v ) { if ( any( lessThan( v, vec3( 0.0 ) ) ) ) { discard; } }
  9: void clip( vec4 v ) { if ( any( lessThan( v, vec4( 0.0 ) ) ) ) { discard; } }
 10: 
 11: float saturate( float v ) { return clamp( v, 0.0, 1.0 ); }
 12: vec2 saturate( vec2 v ) { return clamp( v, 0.0, 1.0 ); }
 13: vec3 saturate( vec3 v ) { return clamp( v, 0.0, 1.0 ); }
 14: vec4 saturate( vec4 v ) { return clamp( v, 0.0, 1.0 ); }
 15: 
 16: uniform sampler2D samp0;
 17: 
 18: in vec2 vofi_TexCoord0;
 19: in vec4 vofi_TexCoord1;
 20: in vec4 vofi_Color;
 21: 
 22: out vec4 fo_FragColor;
 23: 
 24: void main() {
 25: 	vec4 color = ( texture ( samp0 , vofi_TexCoord0 ) * vofi_Color ) + vofi_TexCoord1 ;
 26: 	fo_FragColor . xyz = color. xyz * color. w ;
 27: 	fo_FragColor . w = color. w ;
 28: }
-----------------
ERROR: 0:2: '' :  incorrect GLSL version: 450
WARNING: 0:25: 'function' : is not available in current GLSL version texture


While linking GLSL program 0 with vertexShader gui and fragmentShader gui
Link called without any attached shader objects.

--------- Game Map Shutdown ----------
--------------------------------------
********************
ERROR: While linking GLSL program 0 with vertexShader gui and fragmentShader gui

********************
Unknown command 'vid_restart'
While linking GLSL program 0 with vertexShader gui and fragmentShader gui

Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): success
...deleting GL context: success
...releasing DC: success
...destroying window
```

**Comment by MadDeCoDeR** [comment]
You said that Steam says that it does support 4.6 right ? Are you sure you have installed the latest drivers for the GPU?, like these? https://downloadcenter.intel.com/download/29808/Intel-Graphics-Windows-10-DCH-Drivers?product=88345 (It shows to add support for OpenGL 4.6 . From the latest log it seems that yours support only up to 4.4)

**Comment by SpeedStriker243** [comment]
The drivers you linked apparently are incompatible.

**Comment by MadDeCoDeR** [comment]
Well in that case check your laptop's (you are using a laptop right ? ) manufacturer support website and see if it has newer drivers for the GPU.

**Comment by SpeedStriker243** [comment]
I checked, and apparently it's up to date. I have an NVIDIA GPU with OpenGL 4.6, though. At least I think so. DBFA seems to be using the integrated graphics.

**Comment by SpeedStriker243** [comment]
Figured it out. Just needed to change the settings in the NVIDIA control panel.
