### ISSUE TITLE
Crash on Attempting Doom Games

### ISSUE THREAD

**Issue by d10sfan** [MadDeCoDeR/Classic-RBDOOM-3-BFG#56]
**Describe the bug**
Doom 3 appears to work fine. When I attempt to play Doom 1, once I try to start a new game, it'll crash. If I try to start Doom 2, it'll crash once I click the option in the game selector. This works fine with the same assets on rbdoom-3-bfg. I'm using the steam assets for Doom 3 BFG.

**To Reproduce**
1. Launch the game
2. Click on Doom 1
3. Start a new game
4. Game crashes

**Expected behavior**
Doom 1 and Doom 2 should be able to load into the first level.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version: 1.2.6-BFA

**Additional context**
[qconsole.log](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/files/5176973/qconsole.log)
Log from launch attempt.

**Comment by MadDeCoDeR** [comment]
2 Things: 
1. Be more specific with the system details. I checked Manjaro's website and it has 4 different editions (possible for UI), and I don't know which one you are using.
2. Have you tried to compile it on your system ? The pre-built linux binaries have been compiled on Ubuntu 18.04

**Comment by d10sfan** [comment]
Thanks, I compiled it myself using a Ubuntu 18.04 based VM and it worked fine.
