### ISSUE TITLE
Startup crashes if no sound device is present

### ISSUE THREAD

**Issue by emf2718** [MadDeCoDeR/Classic-RBDOOM-3-BFG#58]
If no sound device is present, startup crashes with "alcOpenDevice() failed".

**To Reproduce**
Disconnect all speakers/headphones
Start Doom 3 BFA

**Expected behavior**
It should start with no sound.

![startup](https://user-images.githubusercontent.com/75904267/101989239-98082980-3c64-11eb-8de9-7c4550712ceb.png)
I don't often have speakers or headphones attached, so this crash occurred.  Starts fine once a sound device is present.

**Comment by MadDeCoDeR** [comment]
Done (is source code). Already tested and both Classic DOOM and DOOM 3 levels are playable.
