### ISSUE TITLE
flashlight bug on weapon change

### ISSUE THREAD

**Issue by TheVoodoo** [MadDeCoDeR/Classic-RBDOOM-3-BFG#6]
switching the flashlight on and off works fine, but when you switch it on and change the weapon the beam stays but the light turns off.

https://youtu.be/fyOmeOSizGE

also tested with previous releases, same problem...
to be on the safe side i checked the flashlight_old parameter, it's 0 (default)

**Comment by TheVoodoo** [comment]
further testing results:
last release without this issue was v1.1.9.6
it seems this bug sneaked in with the introduction of the "flashlight_old" function in 1.1.9.7 rev 1

**Comment by MadDeCoDeR** [comment]
Ok found it and fixed it. Phew, anyway thanks for the feedback

**Comment by TheVoodoo** [comment]
Found out that this bug is still existent, when changing the weapons with the dedicated direct keys on keyboard 1,2,3,...
