### ISSUE TITLE
Ultimate Doom: Lost Souls should be included in the kill count.

### ISSUE THREAD

**Issue by De-Seppe** [MadDeCoDeR/Classic-RBDOOM-3-BFG#60]
Ultimate Doom: Lost Souls should be included in the kill count.

Lost souls attribute to the kill count in Ultimate Doom, this behaviour was removed in Doom 2 due to the Pain Elemental.

Easy testlevel: E2M8, Tower of Babel
Level stats on automap should display 21 on Ultraviolence.

**Comment by MadDeCoDeR** [comment]
Done in commit cb0241586ab34f0f63b591d638e61368fe2f0efa
