### ISSUE TITLE
-timedemo does not play/time demo

### ISSUE THREAD

**Issue by Xymph** [MadDeCoDeR/Classic-RBDOOM-3-BFG#64]
**Describe the bug**
After recording a demo, -playdemo to view it works, but -timedemo to time it doesn't: a black screen is shown, which can be exited by traversing the (invisible) menu, and no tics count message is shown.

**To Reproduce**
1. Start a command prompt window and go into Steam's D3BFG folder which has BFA installed.
2. Record a demo on (e.g.) Nerve map01: DoomBFA -record nervemap01 -exp 2 -warp 1
3. Time it: DoomBFA -timedemo nervemap01
3. After selecting DoomII in the main BFG screen, a black screen appears but nothing happens for 10-15 minutes.
4. Hitting Esc, cursor Up, Enter, Enter allows to close the game cleanly.

**Expected behavior**
A timed playback of the demo (usually without fps limiter), ending in a message with the number of gametics in the demo (and optionally realtics and FPS). That's how other Doom ports do it at least.

**Desktop (please complete the following information):**
 - OS: Win7 64-bit

**Additional context**
View demo: DoomBFA -playdemo nervemap01
After selecting DoomII in the main screen, this plays back the demo as expected (although it desyncs within a few minutes, which is probably a separate problem).

**Comment by MadDeCoDeR** [comment]
I will have to undust a little bit the Demo code and do some tests on my own. Thanks for the feedback.
As for the desync, make sure you are not toying with the settings while it's playing.

**Comment by MadDeCoDeR** [comment]
One issue I found is that the file name has more than 8 characters. On Classic DOOM files must be named with max 8 chars. Also I mentioned another bug that might be causing desync issues

**Comment by Xymph** [comment]
Oh, confession time: the actual filename I used was 'ttt' as a quick first go. But that sounded too silly for this report, so I changed it, only here. ;)
I recorded another demo with "-doom -record doome1m8 -warp 1 8" but it exhibits the same -timedemo behavior as the Nerve map01 one. Just doesn't desync in playback but it runs for only 3:08 -- the Nerve one lasts 8:06.

**Comment by MadDeCoDeR** [comment]
Ok, as for the timedemo. What you are trying to achieve with it? When any demo plays or is getting recorded the engine is forced to the original framerate (35FPS) for compatibility reasons. Also the ENDOOM screen is not available in the first place.

**Comment by Xymph** [comment]
I added support for this demo format in my [stats package](https://github.com/Xymph/LmpStats), and would like to confirm the exact tics count in demo samples with the engine's count.

**Comment by MadDeCoDeR** [comment]
I see. Ok, then I will try to rewrite -timedemo command in order to output in a text file demo's statistics. (I think the original code for it might be removed)

**Comment by Xymph** [comment]
A file is one option, other ports just display a pop-up box, or a console message, or an exit message in the command window.

**Comment by MadDeCoDeR** [comment]
The source code is updated and -timedemo aside from playing the demo, in it's end it will generate a .txt file in the same folder and with the same name the demo has (aka usually in C:\Users\<username>\Saved Games\Id Software\DOOM BFA\<base or name of D3 mod>\DEMO)

**Comment by Xymph** [comment]
Thanks. I'm unable to build BFA from source, so I'll try it after the next binaries release.

**Comment by MadDeCoDeR** [comment]
That's gonna take some time. I want to add two new features and they require quite some work (even through some basics are done)

**Comment by Xymph** [comment]
I understand, no problem. Thanks again for attending to this small issue so quickly.

**Comment by MadDeCoDeR** [comment]
Is now available. (I hope I didn't break it)

**Comment by MadDeCoDeR** [comment]
Are you sure the lmp is on C:\Users\ "username"\Saved Games\Id Software\DOOM BFA\ "base or name of D3 mod"\DEMO folder?

**Comment by MadDeCoDeR** [comment]
Also make sure that you have either finished the level or died in order to finish the demo recording

**Comment by Xymph** [comment]
Oops, I hastily forgot to look in that folder. Yes, `nerve02.lmp` was written there, I did finish the level. But as before, after copying to the game directory, it doesn't playdemo or timedemo.

**Comment by MadDeCoDeR** [comment]
Load it from the same directory that is written

**Comment by Xymph** [comment]
That is a very long path, annoying to type. And the file exists in both DEMO and game directories anyway, so why should that matter? The game can most easily be invoked in a command prompt window after first cd-ing to the game directory. In other ports, the game will load the demo from the local directory, without path or extension, too.

If you can actually play back / time a demo, please explain the detailed steps.

**Comment by MadDeCoDeR** [comment]
Well I used the -record command like you do. And then I used either the -playdemo or -timedemo followed by the name of the demo lump (I haven't moved it from the folder). So it's something like DoomBFA -playdemo nerve02

**Comment by Xymph** [comment]
I didn't move it, see "copying" above. ;)
Anyway, I don't understand why it didn't work before or does now, but... it does. :sweat_smile:  Playback and timing, with a nerve02.txt file created:
```
GameTics: 17428
Level Tics: 17428
Level Time: 497
FPS: 35
```
Looks like these are the tics/time until level end, rather than the total length of the demo, as I stopped recording a second into the next level. So [my stats](https://github.com/Xymph/LmpStats) are 17445 / 498.43s. But that's fine, I understand your choice of where to wrap up the timing and write out the file.

So thanks for your work on this, this issue can be closed. :+1:
