### ISSUE TITLE
Achievements won't trigger in GOG release

### ISSUE THREAD

**Issue by inzsome** [MadDeCoDeR/Classic-RBDOOM-3-BFG#70]
Problems with the GOG release led me to Doom 3 BFA which I installed by following the instructions in the included text file. I'm using Windows 10 on version 21H1 (OS Build 19043.1288).

However, achievements do not seem to trigger in the GOG release of Doom 3 BFG.
I tried it using the Doom achievement "DOOM Burning out of Control", where you have to "complete any DOOM level with 100% kills, items and secrets in single player". I also tried it with the "DOOM II Burning out of Control" achievement, which has the same objective.

I also tried using Open Platform by placing the DLLs in the /base folder of the game.
In the change log for version 1.22 is stated
> Get console message why the achievement didn't unlock

If I start the game with console enabled, I get an error message whenever I complete the objective, telling me that achievements are disables due to console being enabled, so clearly, the game is somehow registering something.

How can I make the GOG release of Doom 3 BFG and Doom 3 BFA compatible, so achievements will trigger properly?

I attached my qconsole.log file.

[qconsole.log](https://github.com/MadDeCoDeR/Classic-RBDOOM-3-BFG/files/7494479/qconsole.log)

Thanks in advance.

**Comment by MadDeCoDeR** [comment]
Doom BFA's support for achievements is relying on both the Open Platform and the API Open Platform uses. As of now there is no GOG Galaxy Open Platform implementation which means that you can't unlock achievements on the GOG Galaxy. Sadly unlike Steam API which is quite easy to get and it uses the public appId for game association, GOG Galaxy's API requires approval from CDPR in order to access and it uses both the public app id but also a private app secret (which I don't have access to)

**Comment by inzsome** [comment]
I see. Would you mind changing the part of the readme where it says

"Steam & GOG API:
The Doom BFA Edition GPL Source Code release does include functionality for integrating with Steam & Discord through Open Platform Api. This includes only achievements and the overlay."

Simply removing "GOG API" from the headline would no longer suggest that the GOG API is supported.
Alternatively, a note could be added that the GOG API would work in theory by suppling the mentioned IDs plus approval by CDPR/GOG.

Thanks.

**Comment by MadDeCoDeR** [comment]
I'm closing this issue since there might be no way to be done
