### ISSUE TITLE
Crashes to desktop. All source ports crash. Only Doom3BFG.exe runs.

### ISSUE THREAD

**Issue by yum13241** [MadDeCoDeR/Classic-RBDOOM-3-BFG#71]
**Describe the bug**
A clear and concise description of what the bug is. A CTD occurs.

**To Reproduce**
Start DoomBFA.exe

**Expected behavior**
To be able to play the frickin game.

**Screenshots**

**Desktop (please complete the following information):**
 -Windows 10 Pro
 - Vivaldi Snapshot (Chrome)
 - Version 2493.3

**Additional context**

Other source ports crash. RBDoom3BFG also crashes, but gives me an error about GLSL.

**Comment by MadDeCoDeR** [comment]
Does your GPU support OpenGL 4.5 & GLSL 450 ?

**Comment by MadDeCoDeR** [comment]
You can start by searching about the GPU you have.

**Comment by yum13241** [comment]
Its an iGPU lol. Intel Pentium N3170 is my CPU, and idk what the iGPU OGL is. Everything alwways tries to use **4.4.0**

**Comment by MadDeCoDeR** [comment]
Closing issue since your hardware doesn't meet minimum system requirements (GPU with support for OpenGL 4.5 or above)
