### ISSUE TITLE
building fails due to bad path for openal headers; /neo/openal-soft/include/AL/ does not exist.

### ISSUE THREAD

**Issue by EndlessEden** [MadDeCoDeR/Classic-RBDOOM-3-BFG#72]
**Issue**
When building (on archlinux with cmake), it chooses a hardcoded non-existent location ($project-root/neo/openal-soft/include/AL/) to locate openal headers for the header sound/snd_efxfile.h.

**To Reproduce**
1. configure with cmake (cmake ../Classic-RBDOOM-3-BFG/neo)
2. begin to build (cmake --build build)
3. wait till build reaches "sound/snd_efxfile.h:34:10"

**Expected behavior**
 replace hardcoded path ($project-root/neo/openal-soft/include/AL/) with detected system header path (/usr/include/AL - in my case)

**Comment by MadDeCoDeR** [comment]
If you want to just run BFA try the prebuild binary that comes with the latest release, it's already tested on Ubuntu 20.04 with gcc11 installed and Manjaro 21.0.7 (if I remember the version right).
If you genuine want to build it try to use the cmake-linux-<profile>.sh scripts (or just replicate the command they have) or even check the recently added github actions of the project which also build successfully, debug profile is meant to be used for debuging (slow and has a huge file) while retail profile is meant to be used for regular use and distribution (fast and small)

**Comment by EndlessEden** [comment]
I need to build packages that comply with archlinux packaging standards for a local repository. | using the supplies profiles skips using system libraries and violates archlinux packaging guidelines.

I also misread the issue, and have updated the issue.

**Comment by MadDeCoDeR** [comment]
Do you have installed that package? It seems to be the OpenAL-soft package. https://aur.archlinux.org/packages/openal-git/
I hope that helps with that issue

**Comment by EndlessEden** [comment]
Please ignore my phrasing stupidity. migraine has me a mess.

**Comment by MadDeCoDeR** [comment]
The lib path is ${projectroot}/neo/libs/openal-soft/include/AL

**Comment by MadDeCoDeR** [comment]
> I need to build packages that comply with archlinux packaging standards for a local repository. | using the supplies profiles skips using system libraries and violates archlinux packaging guidelines.

Where it says that? I haven't found any mention about that, am I missing something?

**Comment by MadDeCoDeR** [comment]
The include files should be fixed now. Also libpng and libjpeg got suppot for the current versions. I tested it on Manjaro linux and compiled fine.

**Comment by MadDeCoDeR** [comment]
Build Arch package with OpenAL is already tested and working.

The working PKGBUILD script and required assets (that come from the pre-built releases) can be found here https://github.com/MadDeCoDeR/DOOM-BFA-Arch-pkg
Closing issue
