### ISSUE TITLE
Vulkan Compiling is Broken

### ISSUE THREAD

**Issue by EndlessEden** [MadDeCoDeR/Classic-RBDOOM-3-BFG#73]
When building with 'USE_VULKAN=1', the cmake configurator fails.

looking upstream at the current state of RBDOOM3, they appear to have vulkan completely working.

Alot of checks are missing from the CMakeLists.txt, and the enviorment variable (VK_SDK_PATH) is old and incorrect. "VULKAN_SDK" is the preferred and current variable used. 

please see https://github.com/RobertBeckebans/RBDOOM-3-BFG/blob/master/neo/CMakeLists.txt#L362 for more info

**Comment by MadDeCoDeR** [comment]
Vulkan build is very unstable and in a very early state. It's inherited by RBDOOM 1.2 and I haven't manage to fully utilize it yet. It's heavily NOT recommended to be used for build

**Comment by MadDeCoDeR** [comment]
Just Updated code to work with latest SDK 959e5ff089968d90849008f74967a17bddef731b. Don't expect it to run perfectly though
