### ISSUE TITLE
neo/renderer/Image_files.cpp | Use of Depreciated API calls to libpng breaks building against recent versions of libpng.

### ISSUE THREAD

**Issue by EndlessEden** [MadDeCoDeR/Classic-RBDOOM-3-BFG#76]
neo/renderer/Image_files.cpp attempts to use older and depreciated api calls to libpng which no longer work.

example:
```

/doom-bfa-git/neo/renderer/Image_files.cpp:639:46: error: invalid use of incomplete type ‘png_struct’ {aka ‘struct png_struct_def’}
  639 |                 memcpy( data, ( byte* )pngPtr->io_ptr, length );
```

This specific issue is discussed in another project that relies on libpng, here (https://github.com/rubis-lab/CPSim_linux/issues/1) - I would advise doing the same.

**Comment by MadDeCoDeR** [comment]
Check libpng12 updating libpng requires many more changes

**Comment by MadDeCoDeR** [comment]
Commit 3ee7bef44f7dfa0e6faf5efd52ed67ddd6c32e59 have fixed any compatibility issues with newer versions of libpng (by copy pasting code from RBDOOM). Closing issue
