### ISSUE TITLE
remove crosshair

### ISSUE THREAD

**Issue by nr1995** [MadDeCoDeR/Classic-RBDOOM-3-BFG#77]
Sorry, this is not a bug,
but I just was wondering what your method for removing the crosshair was.
Is there a way to do it from the console?
Thanks.

**Comment by MadDeCoDeR** [comment]
The crosshair on DOOM 3 is getting hidden using the CVAR pm_cursor, The whole process is just to set the cursor state to NONE when the standard crosshair and the grabber crosshair should be active. To look it better search for pm_cursor on this repo

**Comment by nr1995** [comment]
Thanks for replying!
I'm not very good with computers.
Is there an easy way to implement this one feature in my regular RBDoom3BFG game?

**Comment by MadDeCoDeR** [comment]
Only by copy and pasting the code that does that from here to RBDOOM

**Comment by nr1995** [comment]
I don't want to bother you too much, but...
which code, and where should I paste it?

**Comment by MadDeCoDeR** [comment]
This requires some one who know about C/C++ programming. Plus it would require to re-compile RBDOOM

**Comment by nr1995** [comment]
yeah it's beyond me then.
well thanks anyway!

**Comment by MadDeCoDeR** [comment]
Closing the issue since there is nothing else to it
