### ISSUE TITLE
[Classic DOOM]Master Levels WAD generation

### ISSUE THREAD

**Issue by MadDeCoDeR** [MadDeCoDeR/Classic-RBDOOM-3-BFG#80]
**Describe the bug**
The Master Levels WAD is getting generated regardless if the WAD files exists and the expansion menu pass it resulting into CTD.

**To Reproduce**
1. Make sure you don't have MASTERLEVELS.WAD in either the game's <base or mod>/wads folder or in the save's directory <base or mod>/wads folder
2. Similar to Step 1 but for the master folder or master.zip which contains the original master levels
3. Open DOOM BFA
4. Open DOOM 2
5. Start a New Game
6. Select the Master Levels expansion
7. You will get the option to select the difficulty instead of a message telling you that the expansion is missing

**Expected behavior**
After selecting the Master Levels expansion it should have show you the basic error message that the expansion file is missing

**Desktop (please complete the following information):**
 - OS: Any

**Additional context**
The WAD generation should occur ONLY when the game detects either the master folder or the master.zip. And even if the file is trying to get generated upon error it should be deleted.

**Comment by ViperAcidZX** [comment]
I have all of the master levels WAD files in the master folder within the <DOOM3BFG>\base\wads folder and it is not generating anything now.

**Comment by MadDeCoDeR** [comment]
Thanks for the feedback. This also help me to resolve and another issue. At worst in an hour from now the nightly build will be ready
