### ISSUE TITLE
Jagged shadows on people with Soft Shadows off

### ISSUE THREAD

**Issue by forealdo25** [MadDeCoDeR/Classic-RBDOOM-3-BFG#85]
I've heard how having Soft Shadows on can cause shadows artifacts, and for some shadows to disappear entirely. So I thought I'd play with them off. However, I noticed that that causes shadows cast on people to be really jagged looking.

SS Off
![20220617170411_1](https://user-images.githubusercontent.com/47656512/174414175-33740db1-f87c-4386-ae3a-8e3bd2d70643.jpg)

SS On
![20220617170418_1](https://user-images.githubusercontent.com/47656512/174414185-4082dcaa-e77d-4645-8293-636da6b82113.jpg)

**Comment by tvanassche** [comment]
Do you have "Half Lambert Lighting" set to enabled? If so, try turning it off.

I also noticed the extremely jagged shadows with soft shadows disabled, but when I disabled "Half Lambert Lighting", the shadows return to their original Doom 3 look.

**Comment by MadDeCoDeR** [comment]
Have you try the latest nightly builds? I have disable the self shadows on stencil shadows and now they should look how they used to

**Comment by forealdo25** [comment]
Hey everyone. Thanks for your suggestions. Unfortunately, I just decided to play Doom 3 without a source port a while ago, so I'm not in a position to really try your fixes. Thanks anyway.

**Comment by MadDeCoDeR** [comment]
Thanks for the response and sorry for been too slow to attemp to fix the issue. I will close that issue since the culprit for the reported issue (self-shadows) is no longer enabled by default and the stencil shadows look like how they were supposed to be
