### ISSUE TITLE
[Doom II] Master Levels doesn't work and always crashes the game

### ISSUE THREAD

**Issue by ViperAcidZX** [MadDeCoDeR/Classic-RBDOOM-3-BFG#88]
**Describe the bug**
Every time I try to install the Master Levels in DOOM BFA v1.2.8 going by its instructions on the readme for the source port, it always crashes when I try to choose Master Levels in Doom II's main menu. No matter what I do, it just crashes the game. I tried different versions of the Doom II IWAD, and I get the same problem. I tried both Steam and GOG.com versions of the Master Level wads, still crashes.

**To Reproduce**
1. Install Master Levels for Doom II based on the instructions provided here.
2. Go into Doom II → Master Levels → Pick a difficulty.
3. Game freeze then crashes.

**Expected behavior**
The Master Levels option to work in this newer build since I didn't have this problem years ago.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Version: DOOM BFA v1.2.8

**Additional context**
This problem happened with the Steam version of BFG Edition.

**Comment by MadDeCoDeR** [comment]
The source code must be ok. Check either your game folder or the save folder (C:\Users\\"username"\Saved Games\Id Software\DOOM BFA\base\wads) if there is any MASTERLEVELS.WAD that is less than 3MB and delete it

**Comment by ViperAcidZX** [comment]
That fixed the issue for me.
