### ISSUE TITLE
Crash to desktop when loading save game.

### ISSUE THREAD

**Issue by Darkvapour** [MadDeCoDeR/Classic-RBDOOM-3-BFG#9]
Hi,

I'm getting a crash to desktop in Classic-RBDoom3-BFG when I'm loading a save game when running Back to Saturn X or a couple of OBLIGE generated levels. The game saves fine but loading the save game crashes to desktop.
This seems to affect both 64-Bit builds and 32-Bit released builds.

Save games made without any custom wads (like BTSX or OBLIGE) work fine.
I'm also using the Doom wads from GoG rather than the BFG wads.

I have also compiled the latest version on Git using CMake and Visual Studio 2017 using the Debugging profile and I have run the game in Visual Studio 2017's debugger to get the Call Stack as the issue happens on that version too, hope it helps.

https://pastebin.com/fFZHAAA1

OS:
Windows 10 17763.55 64-Bit (Version 1809)

**Comment by Darkvapour** [comment]
I'm loading the save games with the mods still loaded.
It also crashes in the same game session (not exiting the game) just making a save and then loading it from the menu crashes for me.

**Comment by MadDeCoDeR** [comment]
I tested both mods and I didn't had any issue with the save files.
Maybe I have to write it a little better in order to avoid any further confusion.
If you have a save file that you made using the vanilla maps, and you try to load it while using map mods, the game will crash. That is happening because it let you to load save files if you have loaded the same mods that you used when you made it, and it ignores additional mods.

**Comment by Darkvapour** [comment]
Sorry, I should clarify that I'm saving the game with the mods loaded and loading the game with the mods loaded. I'm not loading vanilla maps at all. But if you've tested it and works fine on your end then it's probably something on my end causing it.

Here's a quick video of the crash happening for me:
https://youtu.be/T_wMvabJ8a8

**Comment by MadDeCoDeR** [comment]
Well, I find the issue. As it seems the save file mod check system was little loose, and when using the easiest difficulty it causes a memory overflow that cause the game to crash.
The good news is that I found the issue and fixed it. I will release it tomorrow.

**Comment by MadDeCoDeR** [comment]
And fixed it.
