### ISSUE TITLE
Flickering lights/lighting with HDR on (Version 1.2.8)

### ISSUE THREAD

**Issue by smeep0** [MadDeCoDeR/Classic-RBDOOM-3-BFG#93]
When running the game with HDR On with the new lighting system, lights will occassionally dim/flicker even though no flickering should occur i.e beginning sections of the game.

I have tried switching the other options (SSAO, soft-shadows, etc.) on and off, restarting the game each time, and can confirm the HDR implementation is mostly the culprit.

**To Reproduce**
1. Turn on HDR from within the game settings
2. Best example is through opening scanner sequence, but the flicker is prominent just from looking around the UAC Mars complex (moving around mouse view might). When standing still (and not moving mouse), image doesn't flicker.

**Desktop:**
 - OS: Windows 11 Pro 22H2
 - CPU: AMD Ryzen 7 5700X
 - GPU: Nvidia RTX 3060 Ti 8GB 
 - RAM: 64GB

**Additional context**
Has this issue been solve in any of the later builds? How soon until the next stable build is released?

**Comment by MadDeCoDeR** [comment]
Sadly the nightly builds don't seem to have that issue resolved, you are ofcourse welcome to try them though.
I don't know when the next release will come out, I'm trying to fix as many issues as possible before I make a new release, sadly those issues take time in order to be fixed.

**Comment by MadDeCoDeR** [comment]
Just a small workaround note: Lowering the brightness makes the flickering less noticable (I don't know if it will work with the stable or only with the nightlies)

**Comment by smeep0** [comment]
Lowering the brightness makes things look a tad too dark. My display is HDR compliant, so the flickering is still noticable.

Is there a way to install the nightly builds? Do I just copy them over a fresh install of Doom 3 BFG Edition?

**Comment by MadDeCoDeR** [comment]
A fresh install with the .resources from the stable

**Comment by smeep0** [comment]
I did a fresh install, copied the stable version over the base game, then copied the nightly build over while ommiting it's /base folder. I wasn't sure if I did it correctly or not, since now some menu options appear broken (Advance Graphics and other options show up as #advance_graphics and whatnot).

**Comment by MadDeCoDeR** [comment]
> I did a fresh install, copied the stable version over the base game, then copied the nightly build over while ommiting it's /base folder. I wasn't sure if I did it correctly or not, since now some menu options appear broken (Advance Graphics and other options show up as #advance_graphics and whatnot).

The broken settings are caused because the /base folder from the nightly you downloaded has updated string files with the new settings Strings (also that base folder contains additional wad files that you need to properly play DOOM 1 & 2)

**Comment by MadDeCoDeR** [comment]
Check the latest nightly builds. The issue seems to be happening with the auto exposure implementation.

**Comment by smeep0** [comment]
I know this sounds like a stupid question, but how does one go about installing the latest nightly build?
I tried installing the latest stable release, and then the Nightly Build overwriting anything on top of that. Am I doing it wrong?

**Comment by MadDeCoDeR** [comment]
Nope, that's how you install the Nightly builds. Just overwrite the files from stable with the ones from Nightly.

NOTE: After some extra testing you might need to boot it twice in order the autoexposure cvar to change

**Comment by smeep0** [comment]
Just tried it right now.

Was able to disable the half-lambert lighting after bootiung twice as mentioned. That said, it did not solve the issue of everything appearing too dark.

It's almost as if stencil shadows have been disabled by disabling all stencil light sources.

**Comment by MadDeCoDeR** [comment]
Main issue is resolved. Secondary issue is also available on #94.
Closing issue
